"""Tests for the LLM system prompt (plan 012).

The load-bearing one is :func:`test_every_sql_example_compiles`: the prompt is
a contract with a model, so every query it shows off must actually compile.
The marker convention is a fenced ``sql`` block -- prompt.py only ever puts
complete, accepted queries inside one.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

import pytest

from sqlmpeg import cli
from sqlmpeg.compiler import compile_sql
from sqlmpeg.errors import ErrorCode, SqlmpegError
from sqlmpeg.prompt import build_system_prompt
from sqlmpeg.stdlib import FUNCTIONS

ROOT = Path(__file__).resolve().parent.parent
DOC_PATH = ROOT / "docs" / "system-prompt.md"
GEN_SCRIPT = ROOT / "scripts" / "gen_prompt.py"

_SQL_FENCE_RE = re.compile(r"```sql\n(.*?)\n```", re.DOTALL)

PROMPT = build_system_prompt()


def _sql_examples(text: str) -> list[str]:
    return _SQL_FENCE_RE.findall(text)


# ---------------------------------------------------------------------------
# the examples are real
# ---------------------------------------------------------------------------


def test_prompt_has_examples() -> None:
    assert len(_sql_examples(PROMPT)) >= 8


@pytest.mark.parametrize("query", _sql_examples(PROMPT))
def test_every_sql_example_compiles(query: str) -> None:
    try:
        graph = compile_sql(query)
    except SqlmpegError as err:  # pragma: no cover - failure path
        pytest.fail(f"prompt example does not compile: {err}\n{query}")
    assert graph.output


def test_examples_cover_the_headline_constructs() -> None:
    joined = "\n".join(_sql_examples(PROMPT))
    for construct in ("WITH ", "UNION ALL", "WHERE ", "BETWEEN ", "overlay(", "blur_regions("):
        assert construct in joined, construct


# ---------------------------------------------------------------------------
# generated from the real surface
# ---------------------------------------------------------------------------


def test_every_function_is_documented() -> None:
    for name, spec in FUNCTIONS.items():
        assert name in PROMPT, name
        assert spec.doc in PROMPT, name


def test_every_parameter_name_and_kind_is_documented() -> None:
    for spec in FUNCTIONS.values():
        for variant in spec.variants:
            rendered = ", ".join(f"{p.name}: {p.kind}" for p in variant)
            assert f"{spec.name}({rendered})" in PROMPT, spec.name


def test_every_error_code_has_repair_guidance() -> None:
    for code in ErrorCode:
        assert f"`{code.value}`" in PROMPT, code.value


def test_prompt_is_deterministic() -> None:
    assert build_system_prompt() == build_system_prompt()


def test_prompt_is_ascii_and_has_no_trailing_newline() -> None:
    PROMPT.encode("ascii")
    assert PROMPT == PROMPT.rstrip("\n")
    assert "\r" not in PROMPT


def test_prompt_states_the_output_rule() -> None:
    assert "Output only the query text." in PROMPT
    assert "validate --json" in PROMPT


# ---------------------------------------------------------------------------
# the committed doc is fresh
# ---------------------------------------------------------------------------


def test_committed_doc_matches_generator() -> None:
    assert DOC_PATH.exists(), "run: python scripts/gen_prompt.py"

    result = subprocess.run(
        [sys.executable, str(GEN_SCRIPT)],
        capture_output=True,
        text=True,
        cwd=str(ROOT),
    )
    assert result.returncode == 0, result.stderr
    assert result.stdout.startswith("unchanged:"), (
        "docs/system-prompt.md is stale; run: python scripts/gen_prompt.py"
    )


def test_committed_doc_uses_lf_and_contains_the_prompt() -> None:
    raw = DOC_PATH.read_bytes()
    assert b"\r\n" not in raw
    text = raw.decode("utf-8")
    assert text.startswith("<!-- Generated by scripts/gen_prompt.py")
    assert PROMPT in text


def test_doc_examples_compile_too() -> None:
    """Guards the doc even if it somehow drifts from the builder."""
    examples = _sql_examples(DOC_PATH.read_bytes().decode("utf-8"))
    assert examples
    for query in examples:
        compile_sql(query)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def test_cli_prompt_prints_it(capsys: pytest.CaptureFixture[str]) -> None:
    code = cli.main(["prompt"])
    captured = capsys.readouterr()
    assert code == 0
    assert captured.err == ""
    assert captured.out == PROMPT + "\n"


def test_cli_prompt_takes_no_query_argument() -> None:
    with pytest.raises(SystemExit) as exc_info:
        cli.main(["prompt", "query.sql"])
    assert exc_info.value.code == 2
