"""Write ``docs/system-prompt.md`` from ``sqlmpeg.prompt.build_system_prompt``.

The committed markdown file is the human-browsable copy of what
``sqlmpeg prompt`` prints; ``tests/test_prompt.py`` asserts the two are in
sync, so run this after touching ``sqlmpeg/prompt.py`` or the stdlib table.

Idempotent: the prompt builder is pure, so re-running rewrites identical
bytes. Newlines are forced to ``\\n`` on every platform.

Usage::

    python scripts/gen_prompt.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from sqlmpeg.prompt import build_system_prompt  # noqa: E402

OUTPUT_PATH = ROOT / "docs" / "system-prompt.md"

HEADER = (
    "<!-- Generated by scripts/gen_prompt.py -- do not edit by hand.\n"
    "     Regenerate with: python scripts/gen_prompt.py\n"
    "     The same text is printed by: sqlmpeg prompt -->\n"
)


def render() -> str:
    """Full file contents: generated-file header, then the prompt."""
    return f"{HEADER}\n{build_system_prompt()}\n"


def main() -> int:
    text = render()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    # Compare raw bytes: Path.read_text would translate newlines on Windows and
    # report a spurious diff against the LF bytes we write.
    previous = OUTPUT_PATH.read_bytes() if OUTPUT_PATH.exists() else None
    if previous == text.encode("utf-8"):
        print(f"unchanged: {OUTPUT_PATH}")
        return 0
    OUTPUT_PATH.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote: {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
