"""End-to-end exec tests: compile sqlmpeg queries and run them through real
ffmpeg against synthetic fixtures generated by ``scripts/gen_fixtures.py``.

Marked ``@pytest.mark.exec`` (registered in ``pyproject.toml``); excluded
from the default test run via ``addopts = -m "not exec"``. Run explicitly::

    python -m pytest -m exec tests/exec -q

Requires ``ffmpeg``/``ffprobe`` on PATH and the fixtures already generated
(``python scripts/gen_fixtures.py``). Tests skip cleanly if either is
missing.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

import imagehash
import pytest
from PIL import Image

from sqlmpeg import cli, loudnorm
from sqlmpeg.compiler import compile_sql
from sqlmpeg.emit import build_ffmpeg_args, build_ffmpeg_commands, emit
from sqlmpeg.errors import SqlmpegError
from sqlmpeg.lower import lower_table
from sqlmpeg.parser import parse, resolve
from sqlmpeg.probe import probe
from sqlmpeg.types import DISPOSITION_KEYS

pytestmark = pytest.mark.exec

_FIXTURES_DIR = Path(__file__).resolve().parent.parent / "fixtures"
_TESTSRC = _FIXTURES_DIR / "testsrc.mp4"
_FRAME_PNG = _FIXTURES_DIR / "frame.png"
_AV = _FIXTURES_DIR / "av.mp4"
_AV2 = _FIXTURES_DIR / "av2.mp4"
_AV3 = _FIXTURES_DIR / "av3.mp4"
# The one fixture with a genuinely 2-CHANNEL audio track (440 Hz
# left, 880 Hz right), which is what channelsplit needs to split.
_STEREO = _FIXTURES_DIR / "stereo.mp4"
# Caption fixtures: avs.mkv is video + audio + an srt track tagged
# language=eng; subs.en.vtt is a standalone 3-cue WebVTT file (no tags).
_AVS = _FIXTURES_DIR / "avs.mkv"
_SUBS_VTT = _FIXTURES_DIR / "subs.en.vtt"
# Video + audio carrying container tags (title/artist/date, no comment).
_TAGGED = _FIXTURES_DIR / "tagged.mp4"

_SRC_WIDTH = 320
_SRC_HEIGHT = 240

_SUBPROCESS_TIMEOUT = 60.0
_PHASH_MAX_DISTANCE = 8


# ---------------------------------------------------------------------------
# skip / helper plumbing
# ---------------------------------------------------------------------------


def _require_fixture(path: Path) -> None:
    if not path.exists():
        pytest.skip(f"fixture missing: {path} (run scripts/gen_fixtures.py first)")


@pytest.fixture(autouse=True)
def _require_ffmpeg_tools() -> None:
    if shutil.which("ffmpeg") is None or shutil.which("ffprobe") is None:
        pytest.skip("ffmpeg/ffprobe not found on PATH")


def _sql_path(path: Path) -> str:
    """Render `path` as the body of a SQL string literal.

    Forward slashes even on Windows: ffmpeg accepts them, and it sidesteps
    backslash-escaping inside the SQL string literal entirely.
    """
    return path.resolve().as_posix()


def _compile_and_run(query: str, out_path: Path) -> None:
    graph = compile_sql(query)
    emitted = emit(graph)
    args = build_ffmpeg_args(emitted, str(out_path))
    args.insert(1, "-y")
    result = subprocess.run(
        args, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT
    )
    assert result.returncode == 0, result.stderr
    assert out_path.exists()


def _ffprobe_video_stream(path: Path) -> dict[str, object]:
    args = [
        "ffprobe",
        "-v",
        "error",
        "-select_streams",
        "v:0",
        "-show_entries",
        "stream=width,height",
        "-of",
        "json",
        str(path),
    ]
    result = subprocess.run(
        args, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT
    )
    assert result.returncode == 0, result.stderr
    data = json.loads(result.stdout)
    streams = data["streams"]
    assert streams, f"no video stream found in {path}"
    stream: dict[str, object] = streams[0]
    return stream


def _ffprobe_duration(path: Path) -> float:
    args = [
        "ffprobe",
        "-v",
        "error",
        "-show_entries",
        "format=duration",
        "-of",
        "json",
        str(path),
    ]
    result = subprocess.run(
        args, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT
    )
    assert result.returncode == 0, result.stderr
    data = json.loads(result.stdout)
    return float(data["format"]["duration"])


def _ffprobe_streams(path: Path) -> list[dict[str, object]]:
    args = [
        "ffprobe",
        "-v",
        "error",
        "-show_entries",
        "stream=index,codec_type,codec_name,channels",
        "-show_entries",
        "stream_tags=language",
        "-of",
        "json",
        str(path),
    ]
    result = subprocess.run(
        args, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT
    )
    assert result.returncode == 0, result.stderr
    data = json.loads(result.stdout)
    streams: list[dict[str, object]] = data["streams"]
    return streams


def _ffprobe_chapters(path: Path) -> list[dict[str, object]]:
    args = ["ffprobe", "-v", "error", "-show_chapters", "-of", "json", str(path)]
    result = subprocess.run(
        args, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT
    )
    assert result.returncode == 0, result.stderr
    data = json.loads(result.stdout)
    chapters: list[dict[str, object]] = data["chapters"]
    return chapters


def _ffprobe_audio_dispositions(path: Path) -> list[dict[str, object]]:
    args = [
        "ffprobe",
        "-v",
        "error",
        "-select_streams",
        "a",
        "-show_entries",
        "stream_disposition",
        "-of",
        "json",
        str(path),
    ]
    result = subprocess.run(
        args, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT
    )
    assert result.returncode == 0, result.stderr
    data = json.loads(result.stdout)
    streams: list[dict[str, object]] = data["streams"]
    return streams


def _ffprobe_format_tags(path: Path) -> dict[str, str]:
    args = ["ffprobe", "-v", "error", "-show_entries", "format_tags", "-of", "json", str(path)]
    result = subprocess.run(
        args, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT
    )
    assert result.returncode == 0, result.stderr
    data = json.loads(result.stdout)
    tags: dict[str, str] = data["format"].get("tags", {})
    return tags


def _extract_frame(video: Path, t: float, out_png: Path) -> None:
    args = [
        "ffmpeg",
        "-y",
        "-ss",
        str(t),
        "-i",
        str(video),
        "-frames:v",
        "1",
        str(out_png),
    ]
    result = subprocess.run(
        args, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT
    )
    assert result.returncode == 0, result.stderr
    assert out_png.exists()


# ---------------------------------------------------------------------------
# tests
# ---------------------------------------------------------------------------


def test_scale_reports_expected_dimensions(tmp_path: Path) -> None:
    _require_fixture(_TESTSRC)
    out_path = tmp_path / "scaled.mp4"
    query = (
        f"SELECT scale(a.video[1], 'iw/2', 'ih/2') FROM input('{_sql_path(_TESTSRC)}') a"
    )

    _compile_and_run(query, out_path)

    stream = _ffprobe_video_stream(out_path)
    assert stream["width"] == _SRC_WIDTH // 2
    assert stream["height"] == _SRC_HEIGHT // 2


def test_trim_reports_expected_duration(tmp_path: Path) -> None:
    _require_fixture(_TESTSRC)
    out_path = tmp_path / "trimmed.mp4"
    query = (
        f"SELECT a.video[1] FROM input('{_sql_path(_TESTSRC)}') a "
        "WHERE a.t BETWEEN 0 AND 1"
    )

    _compile_and_run(query, out_path)

    duration = _ffprobe_duration(out_path)
    assert duration == pytest.approx(1.0, abs=0.2)


# ---------------------------------------------------------------------------
# Input seek: WHERE on an input alias is -ss/-to
#
# Accuracy contract, exec-tested on both sides:
#   * DECODED streams (anything filtered/re-encoded) are frame-accurate --
#     ffmpeg decodes from the preceding keyframe and discards up to the seek
#     point, so the output is exactly the requested window.
#   * STREAM-COPIED streams snap back to the preceding keyframe, so the cut may
#     start up to a GOP early and the output can only be LONGER than the
#     requested window (never shorter), bounded above by the whole input.
#
# Measured keyframe layout of the fixture these bounds are chosen for
# (`ffprobe -select_streams v -show_frames -show_entries frame=key_frame,pts_time`
# on tests/fixtures/testsrc.mp4): 60 frames at 15 fps over 4.000s, and exactly
# ONE keyframe, at pts_time 0.000 -- the GOP is the entire file. A copied
# 0.5..1.5 cut therefore snaps its start all the way back to t=0; the measured
# output duration is 1.367s (requested window 1.0s, whole input 4.0s), which is
# why the copy-path assertion below is a RANGE and not an approx().
# ---------------------------------------------------------------------------

_TRIM_START = 0.5
_TRIM_END = 1.5
_TRIM_WINDOW = _TRIM_END - _TRIM_START
# Slack for container/frame-quantization rounding on both ends of the range
# (one frame at the fixture's 15 fps is 0.067s).
_DURATION_SLACK = 0.1


def test_input_seek_is_frame_accurate_when_the_stream_is_re_encoded(
    tmp_path: Path,
) -> None:
    """The decoded half of the accuracy contract: hflip forces a re-encode, so
    the seek lands exactly on the requested window regardless of keyframes."""
    _require_fixture(_TESTSRC)
    out_path = tmp_path / "reencoded.mp4"
    query = (
        f"SELECT hflip(a.video[1]) FROM input('{_sql_path(_TESTSRC)}') a "
        f"WHERE a.t BETWEEN {_TRIM_START} AND {_TRIM_END}"
    )

    emitted = emit(compile_sql(query))
    args = build_ffmpeg_args(emitted, str(out_path))
    assert args[:6] == ["ffmpeg", "-ss", "0.5", "-to", "1.5", "-i"]

    _compile_and_run(query, out_path)

    assert _ffprobe_duration(out_path) == pytest.approx(_TRIM_WINDOW, abs=_DURATION_SLACK)


def test_a_trimmed_passthrough_is_stream_copied_within_keyframe_tolerance(
    tmp_path: Path,
) -> None:
    """The new capability: `SELECT a.video[1] ... WHERE` stream-copies.

    A window used to splice a trim filter, forcing a re-encode; the src ref
    now survives lowering untouched, so the output is `-map` +
    `-c:0 copy` with the window as input options -- and the duration obeys the
    copy half of the accuracy contract (see the measured keyframe layout above:
    at least the requested window, at most the whole input).
    """
    _require_fixture(_TESTSRC)
    out_path = tmp_path / "copied.mp4"
    query = (
        f"SELECT a.video[1] FROM input('{_sql_path(_TESTSRC)}') a "
        f"WHERE a.t BETWEEN {_TRIM_START} AND {_TRIM_END}"
    )

    emitted = emit(compile_sql(query))
    assert emitted.filter_complex == ""  # nothing decodes: a trimmed remux
    assert emitted.input_trims == [(_TRIM_START, _TRIM_END)]
    args = build_ffmpeg_args(emitted, str(out_path))
    assert args[:7] == ["ffmpeg", "-ss", "0.5", "-to", "1.5", "-i", _sql_path(_TESTSRC)]
    assert "-c:0" in args and args[args.index("-c:0") + 1] == "copy"

    _compile_and_run(query, out_path)

    source_duration = _ffprobe_duration(_TESTSRC)
    duration = _ffprobe_duration(out_path)
    assert duration >= _TRIM_WINDOW - _DURATION_SLACK
    assert duration <= source_duration + _DURATION_SLACK


# ---------------------------------------------------------------------------
# open-ended windows -- WHERE <alias>.t >= x / <= y, no BETWEEN
# ---------------------------------------------------------------------------


def test_tail_only_input_seek_is_frame_accurate_when_the_stream_is_re_encoded(
    tmp_path: Path,
) -> None:
    """`t >= 1` on the 4.000s fixture, decoded path: no upper bound at all --
    ffmpeg reads to EOF -- so the output is exactly the tail, 4.0 - 1.0 = 3.0s."""
    _require_fixture(_TESTSRC)
    out_path = tmp_path / "tail-reencoded.mp4"
    query = f"SELECT hflip(a.video[1]) FROM input('{_sql_path(_TESTSRC)}') a WHERE a.t >= 1"

    emitted = emit(compile_sql(query))
    args = build_ffmpeg_args(emitted, str(out_path))
    assert args[:4] == ["ffmpeg", "-ss", "1", "-i"]
    assert "-to" not in args

    _compile_and_run(query, out_path)

    source_duration = _ffprobe_duration(_TESTSRC)
    assert _ffprobe_duration(out_path) == pytest.approx(
        source_duration - 1.0, abs=_DURATION_SLACK
    )


def test_tail_only_input_seek_is_stream_copied_within_keyframe_tolerance(
    tmp_path: Path,
) -> None:
    """The passthrough half: no `-to` means ffmpeg reads to EOF regardless, so
    a stream-copied tail trim's duration ranges from the requested tail up to
    the whole input -- same keyframe-snap contract a closed window has (see
    the measured keyframe layout above testsrc.mp4 has one keyframe, at t=0,
    so a copy can only snap all the way back to the start)."""
    _require_fixture(_TESTSRC)
    out_path = tmp_path / "tail-copied.mp4"
    query = f"SELECT a.video[1] FROM input('{_sql_path(_TESTSRC)}') a WHERE a.t >= 1"

    emitted = emit(compile_sql(query))
    assert emitted.filter_complex == ""
    assert emitted.input_trims == [(1, None)]
    args = build_ffmpeg_args(emitted, str(out_path))
    assert args[:4] == ["ffmpeg", "-ss", "1", "-i"]
    assert "-to" not in args

    _compile_and_run(query, out_path)

    source_duration = _ffprobe_duration(_TESTSRC)
    duration = _ffprobe_duration(out_path)
    assert duration >= source_duration - 1.0 - _DURATION_SLACK
    assert duration <= source_duration + _DURATION_SLACK


def test_a_trimmed_captioned_input_still_remuxes_video_and_audio(tmp_path: Path) -> None:
    """A WHERE over a captioned input is fine as long as the captions are not
    selected (they are seeked but unmapped). Selecting them under a trim is
    rejected: measured 2026-08-15, ffmpeg does not retime caption packets
    under an input -ss (copy or transcode), so they would desync."""
    _require_fixture(_AVS)
    out_path = tmp_path / "trimmed-av.mkv"
    query = (
        f"SELECT a.video[1], a.audio[1] FROM input('{_sql_path(_AVS)}') a "
        f"WHERE a.t BETWEEN {_TRIM_START} AND {_TRIM_END}"
    )

    emitted = emit(compile_sql(query))
    assert emitted.filter_complex == ""
    assert [m.target for m in emitted.maps] == ["0:v:0", "0:a:0"]
    assert emitted.input_trims == [(_TRIM_START, _TRIM_END)]

    _compile_and_run(query, out_path)

    streams = _ffprobe_streams(out_path)
    assert [s["codec_type"] for s in streams] == ["video", "audio"]

    with pytest.raises(SqlmpegError) as excinfo:
        compile_sql(
            f"SELECT * FROM input('{_sql_path(_AVS)}') a "
            f"WHERE a.t BETWEEN {_TRIM_START} AND {_TRIM_END}"
        )
    assert "out of sync" in excinfo.value.message


def test_hflip_matches_pil_flipped_source_by_phash(tmp_path: Path) -> None:
    _require_fixture(_TESTSRC)
    out_path = tmp_path / "hflipped.mp4"
    query = f"SELECT hflip(a.video[1]) FROM input('{_sql_path(_TESTSRC)}') a"

    _compile_and_run(query, out_path)

    source_png = tmp_path / "source_frame.png"
    output_png = tmp_path / "output_frame.png"
    _extract_frame(_TESTSRC, 1.0, source_png)
    _extract_frame(out_path, 1.0, output_png)

    with Image.open(source_png) as source_img:
        expected = source_img.transpose(Image.Transpose.FLIP_LEFT_RIGHT)
        expected_hash = imagehash.phash(expected)
    with Image.open(output_png) as output_img:
        actual_hash = imagehash.phash(output_img)

    distance = expected_hash - actual_hash
    assert distance <= _PHASH_MAX_DISTANCE


# ---------------------------------------------------------------------------
# multi-stream: remap-only passthrough and audio broadcasting
# ---------------------------------------------------------------------------


def test_remap_only_stream_copies_the_selected_audio_track(tmp_path: Path) -> None:
    """`a.video[1], a.audio[2]` on a 2-audio-track file: nothing re-encoded.

    av2.mp4 tags its second audio track `language=fra`; a bare subscript with
    zero node consumers must stay a passthrough (-map + -c copy), so the
    output keeps that tag and the exact input codec.
    """
    _require_fixture(_AV2)
    out_path = tmp_path / "remap.mp4"
    query = f"SELECT a.video[1], a.audio[2] FROM input('{_sql_path(_AV2)}') a"

    graph = compile_sql(query)
    emitted = emit(graph)
    assert emitted.filter_complex == ""  # pure passthrough: no filtergraph at all

    args = build_ffmpeg_args(emitted, str(out_path))
    assert "-c:0" in args and "-c:1" in args  # both outputs are stream-copied
    args.insert(1, "-y")
    result = subprocess.run(args, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT)
    assert result.returncode == 0, result.stderr
    assert out_path.exists()

    streams = _ffprobe_streams(out_path)
    assert [s["codec_type"] for s in streams] == ["video", "audio"]
    audio = streams[1]
    assert audio["tags"]["language"] == "fra"
    source_audio = _ffprobe_streams(_AV2)[2]  # a.audio[2] is the fra track (1-based)
    assert audio["codec_name"] == source_audio["codec_name"]


def test_reverb_broadcast_produces_a_tagged_stream_per_language_track(tmp_path: Path) -> None:
    """`aecho(a.audio, 0.8, 0.9, 60, 0.3)` on a 2-audio-track file expands to
    two aecho subgraphs, one per track, and each output keeps its source language tag."""
    _require_fixture(_AV2)
    out_path = tmp_path / "reverb.mp4"
    query = f"SELECT aecho(a.audio, 0.8, 0.9, 60, 0.3) FROM input('{_sql_path(_AV2)}') a"

    _compile_and_run(query, out_path)

    streams = _ffprobe_streams(out_path)
    assert [s["codec_type"] for s in streams] == ["audio", "audio"]
    assert [s["tags"]["language"] for s in streams] == ["eng", "fra"]


# ---------------------------------------------------------------------------
# UNION ALL splat: concat two dual-language sources, tracks paired by position
# ---------------------------------------------------------------------------


def test_union_splat_concatenates_both_language_tracks(tmp_path: Path) -> None:
    """The README headline, end to end.

    Both branches splat `<alias>.audio`, so UNION ALL's column matching pairs
    av2's and av3's tracks elementwise into `concat=n=2:v=1:a=2`. The two files
    tag their tracks eng/fra alike, so both concat audio pads keep the language
    they agree on -- and the run is twice as long as either source.
    """
    _require_fixture(_AV2)
    _require_fixture(_AV3)
    out_path = tmp_path / "season.mp4"
    query = (
        f"SELECT a.video[1], a.audio FROM input('{_sql_path(_AV2)}') a "
        f"UNION ALL "
        f"SELECT b.video[1], b.audio FROM input('{_sql_path(_AV3)}') b"
    )

    _compile_and_run(query, out_path)

    streams = _ffprobe_streams(out_path)
    assert [s["codec_type"] for s in streams] == ["video", "audio", "audio"]
    assert [s["tags"]["language"] for s in streams[1:]] == ["eng", "fra"]
    assert _ffprobe_duration(out_path) == pytest.approx(
        _ffprobe_duration(_AV2) + _ffprobe_duration(_AV3), abs=0.3
    )


# ---------------------------------------------------------------------------
# PiP composite + broadcast-zip mix: the flagship, end to end
# ---------------------------------------------------------------------------


def test_pip_mix_flagship_composites_video_and_keeps_both_language_tags(
    tmp_path: Path,
) -> None:
    """The README headline, end to end.

    `pip` scales commentary down and `overlay`s it onto the film; `volume`
    broadcasts over each file's 2-track audio array and `amix` zips the pairs,
    English with English and French with French. The composited video output
    stays the base film's size (the PiP shrinks, not the frame it lands on);
    both mixed audio outputs keep the language both zipped sides agree on.
    """
    _require_fixture(_AV2)
    _require_fixture(_AV3)
    out_path = tmp_path / "pip.mp4"
    query = (
        "WITH pip AS ("
        f"  SELECT scale(c.video[1], 'iw/4', 'ih/4') AS frame, c.audio AS sound "
        f"  FROM input('{_sql_path(_AV3)}') c"
        ") "
        "SELECT overlay(f.video[1], pip.frame, 20, 20), "
        "       amix(volume(f.audio, 0.65), volume(pip.sound, 0.35)) "
        f"FROM input('{_sql_path(_AV2)}') f, pip"
    )

    _compile_and_run(query, out_path)

    streams = _ffprobe_streams(out_path)
    assert [s["codec_type"] for s in streams] == ["video", "audio", "audio"]
    assert [s.get("tags", {}).get("language") for s in streams[1:]] == ["eng", "fra"]

    video = _ffprobe_video_stream(out_path)
    assert (video["width"], video["height"]) == (_SRC_WIDTH, _SRC_HEIGHT)


# ---------------------------------------------------------------------------
# COPY ... TO ... WITH (...) sink options: end to end
# ---------------------------------------------------------------------------


def test_copy_sink_codec_options_land_in_the_real_encode(tmp_path: Path) -> None:
    """Wrap the union-splat headline in a COPY and check the WITH (...) codec
    options actually reach ffmpeg, not just that the sink dict was built.

    The query concatenates av2 and av3 (splatting each file's whole audio
    array, same as the README headline) and asks for libx264/aac re-encodes
    at explicit bitrates; the sink's own TO path is what `build_ffmpeg_args`
    resolves, and ffprobe on the real output confirms the video and both
    audio streams were actually re-encoded to the requested codecs.
    """
    _require_fixture(_AV2)
    _require_fixture(_AV3)
    out_path = tmp_path / "sink.mkv"
    query = (
        "COPY (\n"
        f"  SELECT a.video[1], a.audio FROM input('{_sql_path(_AV2)}') a\n"
        "  UNION ALL\n"
        f"  SELECT b.video[1], b.audio FROM input('{_sql_path(_AV3)}') b\n"
        f") TO '{_sql_path(out_path)}' WITH (\n"
        "  video_codec 'libx264', crf 28, audio_codec 'aac', audio_bitrate '96k'\n"
        ")"
    )

    graph = compile_sql(query)
    emitted = emit(graph)
    args = build_ffmpeg_args(emitted)  # no override: the sink's own path is used
    args.insert(1, "-y")
    result = subprocess.run(args, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT)
    assert result.returncode == 0, result.stderr
    assert out_path.exists()

    streams = _ffprobe_streams(out_path)
    assert [s["codec_type"] for s in streams] == ["video", "audio", "audio"]
    assert streams[0]["codec_name"] == "h264"
    assert streams[1]["codec_name"] == "aac"
    assert streams[2]["codec_name"] == "aac"


def _ffprobe_video_profile_level(path: Path) -> dict[str, object]:
    args = [
        "ffprobe",
        "-v",
        "error",
        "-select_streams",
        "v:0",
        "-show_entries",
        "stream=profile,level",
        "-of",
        "json",
        str(path),
    ]
    result = subprocess.run(args, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT)
    assert result.returncode == 0, result.stderr
    data = json.loads(result.stdout)
    stream: dict[str, object] = data["streams"][0]
    return stream


def test_profile_level_maxrate_land_in_a_real_encode(tmp_path: Path) -> None:
    """Recipe 35's option batch (profile/level/maxrate/bufsize), run for real:
    ffprobe on the output confirms the encoder actually applied them, not
    just that ffmpeg accepted the flags without complaint."""
    _require_fixture(_TESTSRC)
    out_path = tmp_path / "delivery.mp4"
    query = (
        "COPY (\n"
        f"  SELECT a.video[1] FROM input('{_sql_path(_TESTSRC)}') a\n"
        f") TO '{_sql_path(out_path)}' WITH (\n"
        "  video_codec 'libx264', profile 'baseline', level '3.1', "
        "maxrate '500k', bufsize '1000k'\n"
        ")"
    )
    _run_sink_query(query, out_path)

    stream = _ffprobe_video_profile_level(out_path)
    assert "Baseline" in str(stream["profile"])
    assert stream["level"] == 31  # ffprobe's own spelling of level "3.1"


def test_seek_end_produces_a_shorter_file_than_the_source(tmp_path: Path) -> None:
    """seek_end seeks from EOF: testsrc.mp4 is a known 4.000s, so keeping the
    last second must produce a file shorter than the whole source."""
    _require_fixture(_TESTSRC)
    out_path = tmp_path / "tail.mp4"
    query = (
        f"SELECT a.video[1] FROM input('{_sql_path(_TESTSRC)}', seek_end => 1) a"
    )

    _compile_and_run(query, out_path)

    source_duration = _ffprobe_duration(_TESTSRC)
    tail_duration = _ffprobe_duration(out_path)
    assert tail_duration < source_duration
    assert tail_duration == pytest.approx(1.0, abs=0.3)


# ---------------------------------------------------------------------------
# SELECT *, subtitle streams, external caption joins
# ---------------------------------------------------------------------------


def _run_sink_query(query: str, out_path: Path) -> None:
    """Compile a COPY query and run it at ITS OWN sink path (no override)."""
    emitted = emit(compile_sql(query))
    args = build_ffmpeg_args(emitted)
    args.insert(1, "-y")
    result = subprocess.run(
        args, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT
    )
    assert result.returncode == 0, f"{args}\n{result.stderr}"
    assert out_path.exists()


def test_select_star_remuxes_every_stream_of_a_captioned_file(tmp_path: Path) -> None:
    """`SELECT *` over avs.mkv: video + audio + the eng-tagged subtitle track,
    all passthrough (no filtergraph at all), language tag carried through."""
    _require_fixture(_AVS)
    out_path = tmp_path / "star.mkv"
    query = f"SELECT * FROM input('{_sql_path(_AVS)}') a"

    emitted = emit(compile_sql(query))
    assert emitted.filter_complex == ""  # a star is a pure remux
    assert [m.target for m in emitted.maps] == ["0:v:0", "0:a:0", "0:s:0"]

    _compile_and_run(query, out_path)

    streams = _ffprobe_streams(out_path)
    assert [s["codec_type"] for s in streams] == ["video", "audio", "subtitle"]
    assert streams[2]["tags"]["language"] == "eng"


def test_qualified_star_mixes_with_an_explicit_column(tmp_path: Path) -> None:
    """`SELECT a.*, b.audio[1]`: one alias splatted whole, one column picked."""
    _require_fixture(_AVS)
    _require_fixture(_AV2)
    out_path = tmp_path / "star-mixed.mkv"
    query = (
        f"SELECT a.*, b.audio[1] "
        f"FROM input('{_sql_path(_AVS)}') a, input('{_sql_path(_AV2)}') b"
    )

    _compile_and_run(query, out_path)

    streams = _ffprobe_streams(out_path)
    assert [s["codec_type"] for s in streams] == [
        "video",
        "audio",
        "subtitle",
        "audio",
    ]
    assert streams[2]["tags"]["language"] == "eng"
    assert streams[3]["tags"]["language"] == "eng"  # av2's first track


def test_an_attached_file_never_lands_in_the_data_array(tmp_path: Path) -> None:
    """ffprobe calls an attachment its own codec_type, and `data` is not it.

    `data` is the bucket for what ffprobe cannot classify; an attachment is
    well-typed, so it stays out until it has a column of its own.
    """
    _require_fixture(_AVS)
    attached = tmp_path / "attached.mkv"
    font = tmp_path / "font.txt"
    font.write_text("not really a font\n", encoding="utf-8")
    build = [
        "ffmpeg",
        "-y",
        "-loglevel",
        "error",
        "-i",
        str(_AVS),
        "-attach",
        str(font),
        "-metadata:s:t",
        "mimetype=application/octet-stream",
        "-c",
        "copy",
        str(attached),
    ]
    result = subprocess.run(
        build, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT
    )
    assert result.returncode == 0, result.stderr
    assert any(
        s["codec_type"] == "attachment" for s in _ffprobe_streams(attached)
    ), "the fixture has no attachment to test with"

    probed = probe(str(attached))
    assert probed is not None
    assert [s.type for s in probed.streams] == ["video", "audio", "subtitle"]

    # And the star maps the three real streams, never a fourth.
    query = f"SELECT * FROM input('{_sql_path(attached)}') a"
    emitted = emit(compile_sql(query))
    assert [m.target for m in emitted.maps] == ["0:v:0", "0:a:0", "0:s:0"]


def test_vtt_join_muxes_an_external_caption_track_into_an_mkv(tmp_path: Path) -> None:
    """An external WebVTT file joined as a subtitle track.

    Two inputs, three columns, no new join semantics -- the SELECT list IS the
    -map list, and `subtitle_codec 'srt'` transcodes webvtt into the mkv.
    """
    _require_fixture(_AVS)
    _require_fixture(_SUBS_VTT)
    out_path = tmp_path / "joined.mkv"
    query = (
        "COPY (\n"
        f"  SELECT f.video[1], f.audio[1], s.subtitle[1]\n"
        f"  FROM input('{_sql_path(_AVS)}') f, input('{_sql_path(_SUBS_VTT)}') s\n"
        f") TO '{_sql_path(out_path)}' WITH (subtitle_codec 'srt')"
    )

    _run_sink_query(query, out_path)

    streams = _ffprobe_streams(out_path)
    assert [s["codec_type"] for s in streams] == ["video", "audio", "subtitle"]
    assert streams[2]["codec_name"] == "subrip"
    # The .vtt fixture carries no language tag of its own, and provenance never
    # invents one: the joined caption track is untagged.
    assert "language" not in streams[2].get("tags", {})


def test_vtt_join_transcodes_to_mov_text_in_an_mp4(tmp_path: Path) -> None:
    """The same join into an mp4, where mov_text is the only legal caption codec."""
    _require_fixture(_AVS)
    _require_fixture(_SUBS_VTT)
    out_path = tmp_path / "joined.mp4"
    query = (
        "COPY (\n"
        f"  SELECT f.video[1], f.audio[1], s.subtitle[1]\n"
        f"  FROM input('{_sql_path(_AVS)}') f, input('{_sql_path(_SUBS_VTT)}') s\n"
        f") TO '{_sql_path(out_path)}' WITH (subtitle_codec 'mov_text')"
    )

    _run_sink_query(query, out_path)

    streams = _ffprobe_streams(out_path)
    assert [s["codec_type"] for s in streams] == ["video", "audio", "subtitle"]
    assert streams[2]["codec_name"] == "mov_text"


def test_subtitle_extraction_writes_a_parseable_srt_file(tmp_path: Path) -> None:
    """`COPY (SELECT f.subtitle[1]) TO 'x.srt'` -- extraction falls out of sinks."""
    _require_fixture(_AVS)
    out_path = tmp_path / "captions.srt"
    query = (
        "COPY (\n"
        f"  SELECT f.subtitle[1] FROM input('{_sql_path(_AVS)}') f\n"
        f") TO '{_sql_path(out_path)}'"
    )

    _run_sink_query(query, out_path)

    text = out_path.read_text(encoding="utf-8")
    # SubRip: numbered cues with `hh:mm:ss,mmm --> hh:mm:ss,mmm` timings.
    assert text.lstrip().startswith("1\n") or text.lstrip().startswith("1\r\n")
    assert " --> " in text
    assert "Cue one." in text
    # ffprobe agrees it is a subtitle stream, i.e. the file really parses.
    streams = _ffprobe_streams(out_path)
    assert [s["codec_type"] for s in streams] == ["subtitle"]


# ---------------------------------------------------------------------------
# the ad insert -- a video delay composed with overlay
# ---------------------------------------------------------------------------
#
# `delay(f, s)` on VIDEO is format=yuva420p + tpad=start_duration=s:stop=1,
# i.e. a transparent canvas: empty for `s` seconds, then the clip, then one
# transparent frame that overlay's `repeatlast` holds for the rest of the base.
# These two tests are the reason that shape was chosen -- they check the
# composite really does run to completion and really is transparent on both
# sides of the clip.

# The overlay rectangle of the queries below: a 0.33-scaled 320x240 clip
# (105x79 after scale's even-height rounding) placed at (20, 20). Sampled a few
# pixels inside its edges so a one-pixel rounding difference cannot matter.
_PIP_BOX = (24, 24, 120, 94)

# Mean per-channel difference over `_PIP_BOX`, in 0..255. The composite and the
# bare base go through different filter chains, so "identical" is a small
# number rather than zero; "the clip is visible" is a large one.
_PIP_SAME = 6.0
_PIP_DIFFERENT = 20.0


def _pip_bytes(path: Path) -> bytes:
    with Image.open(path) as img:
        return img.convert("RGB").crop(_PIP_BOX).tobytes()


def _pip_difference(left: Path, right: Path) -> float:
    """Mean per-channel difference over the overlay rectangle, in 0..255."""
    a, b = _pip_bytes(left), _pip_bytes(right)
    assert len(a) == len(b) > 0
    return sum(abs(x - y) for x, y in zip(a, b)) / len(a)


def test_ad_insert_composites_a_delayed_clip_over_the_film(tmp_path: Path) -> None:
    """The ad-insert driving case, compiled and RUN.

    A 0.33-scale copy of the ad, delayed one second, composited into the
    film's corner, with its audio delayed by the same second and mixed under
    the film's at half volume. Both fixtures are 4s, so the delayed ad is the
    longer of the two branches and the output runs to delay + ad = 5s.
    """
    _require_fixture(_AV2)
    _require_fixture(_AV3)
    out_path = tmp_path / "ad-insert.mp4"
    query = (
        "SELECT overlay(f.video[1], "
        "sqlmpeg.delay(scale(a.video[1], 'iw*0.33', 'ih*0.33'), 1), 20, 20), "
        "       amix(f.audio[1], volume(adelay(a.audio[1], 1000), 0.5)) "
        f"FROM input('{_sql_path(_AV2)}') f, input('{_sql_path(_AV3)}') a"
    )

    graph = compile_sql(query)
    assert [node.filter for node in graph.nodes.values()] == [
        "scale",
        "format",
        "tpad",
        "overlay",
        "adelay",
        "volume",
        "amix",
    ]
    filter_complex = emit(graph).filter_complex
    assert "format=pix_fmts=yuva420p" in filter_complex
    assert "tpad=start_duration=1:stop=1:color=black@0" in filter_complex

    _compile_and_run(query, out_path)

    streams = _ffprobe_streams(out_path)
    assert [s["codec_type"] for s in streams] == ["video", "audio"]
    assert _ffprobe_duration(out_path) == pytest.approx(
        1 + _ffprobe_duration(_AV3), abs=0.3
    )


def test_a_delayed_video_is_transparent_before_and_after_its_clip(
    tmp_path: Path,
) -> None:
    """The semantics the macro promises, measured pixel by pixel.

    The base here is av2+av3 concatenated (8s), so it outlasts the delayed
    clip (1s + 4s) and there is an "after" to look at. The same base is also
    rendered on its own; the composite must be indistinguishable from it
    inside the overlay rectangle before t=1 and after t=5, and clearly
    different in between. The 8s duration is itself the other half of the
    claim: a transparent canvas that padded FOREVER (tpad stop=-1) would make
    overlay never terminate at all.
    """
    _require_fixture(_AV2)
    _require_fixture(_AV3)
    base_cte = (
        "WITH base AS ("
        f"  SELECT f.video[1] AS v FROM input('{_sql_path(_AV2)}') f "
        "  UNION ALL "
        f"  SELECT g.video[1] AS v FROM input('{_sql_path(_AV3)}') g"
        ") "
    )
    base_path = tmp_path / "base.mp4"
    composite_path = tmp_path / "composite.mp4"

    _compile_and_run(base_cte + "SELECT base.v FROM base", base_path)
    _compile_and_run(
        base_cte
        + "SELECT overlay(base.v, "
        "sqlmpeg.delay(scale(a.video[1], 'iw*0.33', 'ih*0.33'), 1), 20, 20) "
        f"FROM base, input('{_sql_path(_AV3)}') a",
        composite_path,
    )

    # The composite ends WITH the base, not with the never-ending canvas.
    assert _ffprobe_duration(composite_path) == pytest.approx(
        _ffprobe_duration(base_path), abs=0.3
    )

    for moment, expected in ((0.3, "same"), (1.5, "different"), (5.5, "same")):
        base_png = tmp_path / f"base-{moment}.png"
        composite_png = tmp_path / f"composite-{moment}.png"
        _extract_frame(base_path, moment, base_png)
        _extract_frame(composite_path, moment, composite_png)
        difference = _pip_difference(base_png, composite_png)
        if expected == "same":
            assert difference < _PIP_SAME, f"t={moment}: overlay is not transparent"
        else:
            assert difference > _PIP_DIFFERENT, f"t={moment}: the clip is not visible"


def test_the_same_subtitle_track_may_be_mapped_twice(tmp_path: Path) -> None:
    """Duplicate consumption of one subtitle src ref: two Outputs, two identical
    bare -maps, no split filter anywhere (the split/emit exemption)."""
    _require_fixture(_AVS)
    out_path = tmp_path / "twice.mkv"
    query = (
        f"SELECT a.video[1], a.subtitle[1], a.subtitle[1] "
        f"FROM input('{_sql_path(_AVS)}') a"
    )

    emitted = emit(compile_sql(query))
    assert emitted.filter_complex == ""
    assert [m.target for m in emitted.maps] == ["0:v:0", "0:s:0", "0:s:0"]

    _compile_and_run(query, out_path)

    streams = _ffprobe_streams(out_path)
    assert [s["codec_type"] for s in streams] == ["video", "subtitle", "subtitle"]
    assert [s["tags"]["language"] for s in streams[1:]] == ["eng", "eng"]


# ---------------------------------------------------------------------------
# the ad-splice pattern, without the `BETWEEN x AND 3600` placeholder
# ---------------------------------------------------------------------------


def test_ad_splice_tail_trim_needs_no_between_placeholder(tmp_path: Path) -> None:
    """Splice an ad into the middle of a clip by cutting the base into a head
    and a tail, with the tail reaching to the end of the file. That used to mean
    a `BETWEEN x AND 3600`-style placeholder to fake "to the end";
    `g.t >= 1` says it directly, with no upper bound at all.

    Three UNION ALL branches over the 4s av2/av3 fixtures: a 1s head of av2, all
    of av3 as the ad, and a 1s tail of av2 (`g.t >= 1`, BETWEEN-free). Every
    branch feeds the `concat` filter, so every trim is DECODED end to end
    (frame-accurate, not stream-copy-and-snap), and the run is head + ad + tail.
    """
    _require_fixture(_AV2)
    _require_fixture(_AV3)
    av2_path = _sql_path(_AV2)
    av3_path = _sql_path(_AV3)
    out_path = tmp_path / "ad-splice.mp4"
    query = (
        f"SELECT a.video[1] FROM input('{av2_path}') a WHERE a.t BETWEEN 0 AND 1 "
        "UNION ALL "
        f"SELECT b.video[1] FROM input('{av3_path}') b "
        "UNION ALL "
        f"SELECT g.video[1] FROM input('{av2_path}') g WHERE g.t >= 1"
    )

    graph = compile_sql(query)
    assert graph.input_trims == {"a": (0, 1), "g": (1, None)}
    assert [node.filter for node in graph.nodes.values()] == ["concat"]

    emitted = emit(graph)
    args = build_ffmpeg_args(emitted, str(out_path))
    assert args[:13] == [
        "ffmpeg",
        "-ss",
        "0",
        "-to",
        "1",
        "-i",
        av2_path,
        "-i",
        av3_path,
        "-ss",
        "1",
        "-i",
        av2_path,
    ]
    assert args.count("-to") == 1  # only the head branch has an upper bound

    _compile_and_run(query, out_path)

    expected_duration = 1.0 + _ffprobe_duration(_AV3) + (_ffprobe_duration(_AV2) - 1.0)
    assert _ffprobe_duration(out_path) == pytest.approx(expected_duration, abs=0.3)


# ---------------------------------------------------------------------------
# input('path', name => value, ...)
# ---------------------------------------------------------------------------


def test_looped_png_title_card_composites_onto_testsrc(tmp_path: Path) -> None:
    """The flagship input-options case: a still image, looped and given a
    frame rate so it becomes a real video stream, overlaid onto testsrc.mp4.

    `loop => true` + `framerate => 15` render as `-loop 1 -framerate 15`
    before the png's own `-i`; `WHERE p.t <= 2` becomes a `-to 2` input seek
    on that same `-i`, rendered AFTER the options and still before `-i` (the
    order this module's emit.py chose and verified against real ffmpeg).
    `overlay`'s main input is testsrc.mp4 (the fixture's own 4s duration), so
    the composite runs exactly as long as it does regardless of the png's
    (effectively infinite, looped) length -- loop forces the png through the
    encoder rather than a stream copy, hence the wider tolerance.
    """
    _require_fixture(_TESTSRC)
    _require_fixture(_FRAME_PNG)
    out_path = tmp_path / "title-card.mp4"
    query = (
        "SELECT overlay(v.video[1], p.video[1], 20, 20) "
        f"FROM input('{_sql_path(_TESTSRC)}') v, "
        f"input('{_sql_path(_FRAME_PNG)}', loop => true, framerate => 15) p "
        "WHERE p.t <= 2"
    )

    graph = compile_sql(query)
    assert graph.input_options == {"p": {"loop": True, "framerate": 15}}
    assert graph.input_trims == {"p": (None, 2.0)}

    emitted = emit(graph)
    args = build_ffmpeg_args(emitted, str(out_path))
    assert args[:3] == ["ffmpeg", "-i", _sql_path(_TESTSRC)]  # v: no options, no trim
    png_start = args.index("-loop")
    assert args[png_start : png_start + 8] == [
        "-loop", "1",
        "-framerate", "15",
        "-to", "2",
        "-i", _sql_path(_FRAME_PNG),
    ]

    _compile_and_run(query, out_path)

    assert _ffprobe_duration(out_path) == pytest.approx(4.0, abs=0.2)


# ---------------------------------------------------------------------------
# FROM ffmpeg.<source>(...)
# ---------------------------------------------------------------------------


def test_silent_audio_lets_a_generated_segment_concat_with_a_real_clip(
    tmp_path: Path,
) -> None:
    """THE headline of generated sources.

    ffmpeg's `concat` needs every segment to have the same pad shape, so a
    generated video segment cannot join a clip that has audio -- unless
    something supplies the missing track. `ffmpeg.anullsrc(duration => 1)` is
    that something, and it costs one zero-input filter node rather than a
    silent .wav on disk.

    Both generators are `-i`-less: the whole command reads ONE input file, and
    `testsrc2`/`anullsrc` are chain heads inside `-filter_complex`. The result
    is av2 (2s, video + audio) followed by a 1s generated segment.
    """
    _require_fixture(_AV2)
    out_path = tmp_path / "silent-concat.mp4"
    query = (
        f"SELECT f.video[1], f.audio[1] FROM input('{_sql_path(_AV2)}') f "
        "UNION ALL "
        "SELECT t.video[1], s.audio[1] "
        "FROM ffmpeg.testsrc2(duration => 1, size => '320x240', rate => 15) t, "
        "ffmpeg.anullsrc(duration => 1) s"
    )

    graph = compile_sql(query)
    # A source takes no input index: one -i for the one real file.
    assert graph.input_paths == [_sql_path(_AV2)]
    assert graph.sources == {"f": 0}
    assert [node.filter for node in graph.nodes.values()] == [
        "testsrc2",
        "anullsrc",
        "concat",
    ]
    assert graph.nodes["n1"].inputs == []
    assert graph.nodes["n2"].inputs == []

    emitted = emit(graph)
    args = build_ffmpeg_args(emitted, str(out_path))
    assert args.count("-i") == 1
    assert emitted.filter_complex.startswith(
        "testsrc2=duration=1:size=320x240:rate=15[n1];anullsrc=duration=1[n2];"
    )

    _compile_and_run(query, out_path)

    streams = _ffprobe_streams(out_path)
    assert [s["codec_type"] for s in streams] == ["video", "audio"]
    expected = _ffprobe_duration(_AV2) + 1.0
    assert _ffprobe_duration(out_path) == pytest.approx(expected, abs=0.3)


def test_a_color_matte_composites_under_a_padded_clip(tmp_path: Path) -> None:
    """A generated colour matte as the base of a composite: `ffmpeg.color`
    makes a 640x480 backdrop out of nothing, and testsrc.mp4 (320x240) is
    overlaid centred on it. Without sources this needs a PNG on disk."""
    _require_fixture(_TESTSRC)
    out_path = tmp_path / "matte.mp4"
    query = (
        "SELECT overlay(m.video[1], v.video[1], 160, 120) "
        "FROM ffmpeg.color(color => 'navy', size => '640x480', rate => 15, "
        "duration => 2) m, "
        f"input('{_sql_path(_TESTSRC)}') v"
    )

    graph = compile_sql(query)
    assert graph.nodes["n1"].filter == "color"
    assert graph.nodes["n1"].inputs == []
    assert graph.nodes["n1"].args == {
        "color": "navy",
        "size": "640x480",
        "rate": 15,
        "duration": 2,
    }

    _compile_and_run(query, out_path)

    stream = _ffprobe_video_stream(out_path)
    assert stream["width"] == 640
    assert stream["height"] == 480


def test_a_sine_tone_is_a_whole_query_with_no_input_file(tmp_path: Path) -> None:
    """No `-i` at all: the entire command is a filtergraph and one `-map`."""
    out_path = tmp_path / "tone.m4a"
    query = "SELECT s.audio[1] FROM ffmpeg.sine(frequency => 440, duration => 1) s"

    graph = compile_sql(query)
    assert graph.input_paths == []
    assert graph.sources == {}

    emitted = emit(graph)
    args = build_ffmpeg_args(emitted, str(out_path))
    assert "-i" not in args
    assert emitted.filter_complex == "sine=frequency=440:duration=1[out0]"

    _compile_and_run(query, out_path)

    streams = _ffprobe_streams(out_path)
    assert [s["codec_type"] for s in streams] == ["audio"]
    assert _ffprobe_duration(out_path) == pytest.approx(1.0, abs=0.2)


# ---------------------------------------------------------------------------
# the timeline `enable` argument, RUN
# ---------------------------------------------------------------------------
#
# The claim `enable` makes is about individual FRAMES, so it is checked the way
# the delay macro's transparency test checks its canvas: render the query, pull one
# frame from inside the window and one from either side, and diff each against
# the untouched fixture. The fixture is 4s at 15fps, so 0.2 / 1.0 / 1.8 sit
# comfortably clear of the 0.5 and 1.5 edges.

# A region well inside the 320x240 frame, so an edge effect cannot decide it.
_ENABLE_BOX = (40, 40, 280, 200)

# Mean per-channel difference over the sampled region, in 0..255. The filtered
# output has been re-encoded and the fixture has not, so "untouched" is a small
# number rather than zero. Measured against ffmpeg 7.1: 0.74 / 48.86 / 0.71 for
# the blur, 0.69 / 17.96 / 0.26 for the box.
_ENABLE_OFF = 5.0
_ENABLE_ON = 10.0


def _region_difference(left: Path, right: Path, box: tuple[int, int, int, int]) -> float:
    with Image.open(left) as first, Image.open(right) as second:
        a = first.convert("RGB").crop(box).tobytes()
        b = second.convert("RGB").crop(box).tobytes()
    assert len(a) == len(b) > 0
    return sum(abs(x - y) for x, y in zip(a, b)) / len(a)


def _assert_enable_window(
    tmp_path: Path,
    rendered: Path,
    source: Path,
    box: tuple[int, int, int, int],
    label: str,
) -> None:
    """Untouched outside 0.5..1.5, visibly filtered inside it."""
    for moment, expected in ((0.2, "off"), (1.0, "on"), (1.8, "off")):
        rendered_png = tmp_path / f"{label}-out-{moment}.png"
        source_png = tmp_path / f"{label}-src-{moment}.png"
        _extract_frame(rendered, moment, rendered_png)
        _extract_frame(source, moment, source_png)
        difference = _region_difference(rendered_png, source_png, box)
        if expected == "off":
            assert difference < _ENABLE_OFF, (
                f"t={moment}: {label} ran outside its enable window ({difference})"
            )
        else:
            assert difference > _ENABLE_ON, (
                f"t={moment}: {label} did not run inside its enable window ({difference})"
            )


def test_enable_blurs_only_inside_its_timeline_window(tmp_path: Path) -> None:
    """The timeline-`enable` headline, measured frame by frame.

    One filter, one named argument, no trim and no branch: the clip is sharp,
    then blurred for a second, then sharp again.
    """
    _require_fixture(_TESTSRC)
    out_path = tmp_path / "enable-blur.mp4"
    query = (
        "SELECT gblur(a.video[1], 12, enable => 'between(t,0.5,1.5)') "
        f"FROM input('{_sql_path(_TESTSRC)}') a"
    )

    graph = compile_sql(query)
    assert graph.nodes["n1"].filter == "gblur"
    assert graph.nodes["n1"].args == {"sigma": 12, "enable": "between(t,0.5,1.5)"}
    # The commas inside the expression are the filtergraph's own separator, so
    # emit has to escape them -- this is a real command, not just a real graph.
    assert "gblur=sigma=12:enable=between(t\\,0.5\\,1.5)" in emit(graph).filter_complex

    _compile_and_run(query, out_path)
    _assert_enable_window(tmp_path, out_path, _TESTSRC, _ENABLE_BOX, "blur")


def test_a_tier_two_filter_takes_enable_through_the_namespace(tmp_path: Path) -> None:
    """The other admitting path: a raw `ffmpeg.<filter>` call, whose timeline
    flag comes from the same `-filters` line the registry parsed. `drawbox` is
    `T.C` in ffmpeg 7.1."""
    _require_fixture(_TESTSRC)
    out_path = tmp_path / "enable-box.mp4"
    query = (
        "SELECT ffmpeg.drawbox(a.video[1], x => 20, y => 20, width => 120, "
        "height => 90, color => 'red', thickness => 8, "
        "enable => 'between(t,0.5,1.5)') "
        f"FROM input('{_sql_path(_TESTSRC)}') a"
    )

    graph = compile_sql(query)
    assert graph.nodes["n1"].filter == "drawbox"
    assert graph.nodes["n1"].args["enable"] == "between(t,0.5,1.5)"

    _compile_and_run(query, out_path)
    _assert_enable_window(tmp_path, out_path, _TESTSRC, (16, 16, 148, 118), "drawbox")


def test_enable_is_rejected_where_this_ffmpeg_reports_no_timeline_flag() -> None:
    """Against the REAL registry, not a fixture: `scale` is `..C` in ffmpeg 7.1,
    and a generated source has no timeline at all."""
    with pytest.raises(SqlmpegError) as excinfo:
        compile_sql(
            "SELECT scale(a.video[1], 640, 360, enable => 'gt(t,1)') "
            f"FROM input('{_sql_path(_TESTSRC)}') a"
        )
    assert excinfo.value.code.value == "UNKNOWN_FILTER_OPTION"
    assert "no option 'enable'" in excinfo.value.message

    with pytest.raises(SqlmpegError) as excinfo:
        compile_sql(
            "SELECT t.video[1] "
            "FROM ffmpeg.testsrc2(duration => 1, enable => 'gt(t,1)') t"
        )
    assert excinfo.value.code.value == "UNKNOWN_FILTER_OPTION"


# ---------------------------------------------------------------------------
# `expr` slots, RUN, and checked against ffmpeg's types
# ---------------------------------------------------------------------------


def test_a_centered_overlay_runs_without_knowing_either_size(tmp_path: Path) -> None:
    """The motivating case for `expr` slots. `(W-w)/2` is ffmpeg's arithmetic over
    the real pad sizes, so nothing here had to probe anything: a 320x240 clip
    lands dead centre of a 640x480 matte, which the edge samples prove (the clip
    must start at x=160 and end at x=480)."""
    _require_fixture(_TESTSRC)
    out_path = tmp_path / "centered.mp4"
    query = (
        "SELECT overlay(m.video[1], v.video[1], '(W-w)/2', '(H-h)/2') "
        "FROM ffmpeg.color(color => 'navy', size => '640x480', rate => 15, "
        "duration => 2) m, "
        f"input('{_sql_path(_TESTSRC)}') v"
    )

    graph = compile_sql(query)
    assert graph.nodes["n2"].args == {"x": "(W-w)/2", "y": "(H-h)/2"}
    assert "overlay=x=(W-w)/2:y=(H-h)/2" in emit(graph).filter_complex

    _compile_and_run(query, out_path)

    stream = _ffprobe_video_stream(out_path)
    assert (stream["width"], stream["height"]) == (640, 480)

    png = tmp_path / "centered.png"
    _extract_frame(out_path, 1.0, png)
    with Image.open(png) as image:
        pixels = image.convert("RGB")

        def rgb(x: int) -> tuple[int, int, int]:
            value = pixels.getpixel((x, 240))
            assert isinstance(value, tuple) and len(value) == 3
            return value

        # navy is 000080; the mp4 round trip lands within a couple of levels.
        for x in (5, 155, 485, 635):
            red, green, blue = rgb(x)
            assert (red, green) == (0, 0) and 120 < blue < 135, x
        for x in (170, 470):
            assert rgb(x)[:2] != (0, 0), x


def test_expression_crop_and_scale_run(tmp_path: Path) -> None:
    """Two more expr slots end to end: crop to the left half by expression,
    then stretch it back to full width by expression. Both filters get a string
    where a bare number used to be the only thing that fit."""
    _require_fixture(_TESTSRC)
    out_path = tmp_path / "expr-crop.mp4"
    query = (
        "SELECT scale(crop(a.video[1], 'iw/2', 'ih', 0, 0), 'iw*2', 'ih') "
        f"FROM input('{_sql_path(_TESTSRC)}') a"
    )

    _compile_and_run(query, out_path)

    stream = _ffprobe_video_stream(out_path)
    assert (stream["width"], stream["height"]) == (_SRC_WIDTH, _SRC_HEIGHT)


# test_every_expr_slot_maps_to_a_string_typed_ffmpeg_option (the stdlib
# FUNCTIONS-table faithfulness test) is removed rather than respelled: there is
# no stdlib FUNCTIONS table for it to check, and no `expr` ParamKind for it to
# verify -- see the matching removal in tests/test_lower.py.


# ---------------------------------------------------------------------------
# a script with several COPYs is ONE ffmpeg command
# ---------------------------------------------------------------------------


def test_the_abr_ladder_writes_three_files_from_one_invocation(tmp_path: Path) -> None:
    """The wave's headline: a view over av2, three COPYs, one ffmpeg run.

    `master` decodes and normalizes once; two COPYs scale it to their own
    rendition and take its audio, and a third takes the audio alone. The
    command has exactly one `-i` and one `-filter_complex`, and the three
    output files come out of the single invocation with the dimensions each
    COPY asked for -- the audio-only one with no video stream at all.
    """
    _require_fixture(_AV2)
    ladder = tmp_path / "480.mp4"
    small = tmp_path / "240.mp4"
    audio = tmp_path / "audio.m4a"
    query = (
        "CREATE VIEW master AS\n"
        "  SELECT a.video[1] AS v, volume(a.audio[1], 0.9) AS a\n"
        f"  FROM input('{_sql_path(_AV2)}') a;\n"
        "COPY (SELECT scale(m.v, 160, -2), m.a FROM master m)\n"
        f"TO '{_sql_path(ladder)}' WITH (video_codec 'libx264', crf 30, audio_codec 'aac');\n"
        "COPY (SELECT scale(m.v, 80, -2), m.a FROM master m)\n"
        f"TO '{_sql_path(small)}' WITH (video_codec 'libx264', crf 32, audio_codec 'aac');\n"
        "COPY (SELECT m.a FROM master m)\n"
        f"TO '{_sql_path(audio)}' WITH (audio_codec 'aac', audio_bitrate '64k');"
    )

    graph = compile_sql(query)
    emitted = emit(graph)
    args = build_ffmpeg_args(emitted)

    assert args.count("-i") == 1  # ONE decode
    assert args.count("-filter_complex") == 1
    assert len(emitted.groups) == 3
    assert args[-1] == str(audio.resolve().as_posix())

    args.insert(1, "-y")
    result = subprocess.run(
        args, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT
    )
    assert result.returncode == 0, f"{args}\n{result.stderr}"

    for path in (ladder, small, audio):
        assert path.exists(), path

    assert _ffprobe_video_stream(ladder)["width"] == 160
    assert _ffprobe_video_stream(ladder)["height"] == 120
    assert _ffprobe_video_stream(small)["width"] == 80
    assert _ffprobe_video_stream(small)["height"] == 60
    assert [s["codec_type"] for s in _ffprobe_streams(ladder)] == ["video", "audio"]
    assert [s["codec_type"] for s in _ffprobe_streams(small)] == ["video", "audio"]
    assert [s["codec_type"] for s in _ffprobe_streams(audio)] == ["audio"]


def test_two_sinks_may_stream_copy_the_same_audio_track(tmp_path: Path) -> None:
    """The cross-GROUP passthrough exemption, against real ffmpeg.

    Both COPYs bare-map `0:a:0`. There is no `asplit` and no filtergraph at
    all: each file gets `-map 0:a:0 -c:0 copy`, which is a repeated `-map`,
    and ffmpeg writes both.
    """
    _require_fixture(_AV2)
    first = tmp_path / "one.m4a"
    second = tmp_path / "two.m4a"
    query = (
        f"CREATE VIEW track AS SELECT a.audio[1] AS a FROM input('{_sql_path(_AV2)}') a;\n"
        f"COPY (SELECT t.a FROM track t) TO '{_sql_path(first)}';\n"
        f"COPY (SELECT t.a FROM track t) TO '{_sql_path(second)}';"
    )

    graph = compile_sql(query)
    emitted = emit(graph)
    assert graph.nodes == {}
    assert emitted.filter_complex == ""
    assert [group.maps[0].target for group in emitted.groups] == ["0:a:0", "0:a:0"]

    args = build_ffmpeg_args(emitted)
    args.insert(1, "-y")
    result = subprocess.run(
        args, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT
    )
    assert result.returncode == 0, f"{args}\n{result.stderr}"

    for path in (first, second):
        streams = _ffprobe_streams(path)
        assert [s["codec_type"] for s in streams] == ["audio"]
        assert streams[0]["codec_name"] == "aac"  # copied, not re-encoded


# ---------------------------------------------------------------------------
# array-RETURNING filters, against real ffmpeg
# ---------------------------------------------------------------------------
#
# `ffmpeg.channelsplit(...)` and friends are `->N` filters the registry
# excludes; lowering re-admits them from its own table and returns an ARRAY, so the
# result splats, subscripts and broadcasts. These run the real thing: the pad
# count the table computed has to be exactly the pad count ffmpeg builds, or
# the graph does not link at all ("More output link labels specified for
# filter 'channelsplit' than it has outputs").


def test_channelsplit_writes_one_mono_stream_per_channel(tmp_path: Path) -> None:
    """The splat: a 2-channel track becomes two 1-channel output streams."""
    _require_fixture(_STEREO)
    out_path = tmp_path / "channels.mka"
    query = (
        f"COPY (SELECT ffmpeg.channelsplit(a.audio[1]) FROM input('{_sql_path(_STEREO)}') a)\n"
        f"TO '{_sql_path(out_path)}';"
    )

    emitted = emit(compile_sql(query))
    assert "channelsplit" in emitted.filter_complex
    assert len(emitted.groups[0].maps) == 2

    _run_sink_query(query, out_path)

    streams = _ffprobe_streams(out_path)
    assert [s["codec_type"] for s in streams] == ["audio", "audio"]
    assert [s["channels"] for s in streams] == [1, 1]


def test_the_channelsplit_round_trip_mixes_the_channels_back_down(
    tmp_path: Path,
) -> None:
    """split -> a volume per channel -> amix back into one stream.

    The wave's headline shape, and the one that exercises every piece at once:
    one node with two pads, a broadcast subscript out of a CTE column, two
    ordinary tier-1 calls, and a join back. `amix` of two mono streams is one
    mono stream (it keeps its first input's layout, which channelsplit made
    `FL`), so the output is written as WAV -- aac refuses a 1-channel `FL`
    layout, which is an ffmpeg encoder rule, not a graph problem.
    """
    _require_fixture(_STEREO)
    out_path = tmp_path / "remixed.wav"
    query = (
        "CREATE VIEW split AS\n"
        f"  SELECT ffmpeg.channelsplit(a.audio[1]) AS ch FROM input('{_sql_path(_STEREO)}') a;\n"
        "COPY (SELECT amix(volume(s.ch[1], 0.5), volume(s.ch[2], 2.0)) FROM split s)\n"
        f"TO '{_sql_path(out_path)}';"
    )

    emitted = emit(compile_sql(query))
    assert emitted.filter_complex == (
        "[0:a:0]channelsplit[n10][n11];"
        "[n10]volume=volume=0.5[n2];"
        "[n11]volume=volume=2.0[n3];"
        "[n2][n3]amix=inputs=2[out0]"
    )

    _run_sink_query(query, out_path)

    streams = _ffprobe_streams(out_path)
    assert [s["codec_type"] for s in streams] == ["audio"]
    assert streams[0]["channels"] == 1
    assert _ffprobe_duration(out_path) == pytest.approx(4.0, abs=0.2)


def test_acrossover_writes_one_stream_per_band(tmp_path: Path) -> None:
    """Two split frequencies, three bands -- the count rule's arithmetic run
    against the filter that has to agree with it."""
    _require_fixture(_STEREO)
    out_path = tmp_path / "bands.mka"
    query = (
        "COPY (SELECT ffmpeg.acrossover(a.audio[1], split => '500|3000')\n"
        f"      FROM input('{_sql_path(_STEREO)}') a)\n"
        f"TO '{_sql_path(out_path)}';"
    )

    emitted = emit(compile_sql(query))
    assert "acrossover=split=500|3000" in emitted.filter_complex

    _run_sink_query(query, out_path)

    streams = _ffprobe_streams(out_path)
    assert [s["codec_type"] for s in streams] == ["audio", "audio", "audio"]
    assert [s["channels"] for s in streams] == [2, 2, 2]  # bands, not channels


def test_extractplanes_extracts_the_luma_plane_as_grey(tmp_path: Path) -> None:
    """`planes => 'y'` is a one-element array, and what comes out is grey.

    One plane per call is all the option surface allows today: the registry
    types `planes` as an enum (it lists constants), so ffmpeg's own `y+u`
    flags spelling is rejected before the count rule sees it.
    """
    _require_fixture(_TESTSRC)
    out_path = tmp_path / "luma.mp4"
    query = (
        "SELECT ffmpeg.extractplanes(a.video[1], planes => 'y') "
        f"FROM input('{_sql_path(_TESTSRC)}') a"
    )

    _compile_and_run(query, out_path)

    assert [s["codec_type"] for s in _ffprobe_streams(out_path)] == ["video"]
    frame = tmp_path / "luma.png"
    _extract_frame(out_path, 1.0, frame)
    with Image.open(frame) as image:
        data = image.convert("RGB").tobytes()
    pixels = [data[i : i + 3] for i in range(0, len(data), 3)]
    # A luma plane rendered as video is grey: every pixel's channels agree,
    # give or take the yuv420p round trip's chroma rounding.
    assert max(max(p) - min(p) for p in pixels) <= 8


# ---------------------------------------------------------------------------
# chapters: read the array column off a real file; write from a VALUES CTE
# and read that back with ffprobe
# ---------------------------------------------------------------------------


def test_unnest_chapters_prints_the_files_own_chapter_list(
    capsys: pytest.CaptureFixture[str],
) -> None:
    """Recipe 39 against the real fixture: the printed rows are exactly what
    ffprobe reports for the same file, read through the array column."""
    source = _FIXTURES_DIR / "av-chapters.mkv"
    _require_fixture(source)
    query = (
        "SELECT c.index, c.title, c.start_t, c.end_t "
        f"FROM input('{_sql_path(source)}') f, unnest(f.chapters) c"
    )

    assert cli.main([query]) == 0

    printed = capsys.readouterr().out
    expected = _ffprobe_chapters(source)
    assert f"({len(expected)} rows)" in printed
    for position, chapter in enumerate(expected, start=1):
        tags = chapter["tags"]
        assert isinstance(tags, dict)
        title = tags["title"]
        assert isinstance(title, str)
        row = [line for line in printed.splitlines() if line.startswith(f" {position} ")]
        assert len(row) == 1, printed
        assert title in row[0]
        assert f"{float(str(chapter['start_time'])):g}" in row[0]


def test_a_bare_chapters_column_prints_the_whole_list_as_one_cell(
    capsys: pytest.CaptureFixture[str],
) -> None:
    """The array VALUE over a real file: one cell, one record per chapter."""
    source = _FIXTURES_DIR / "av-chapters.mkv"
    _require_fixture(source)
    query = f"SELECT f.chapters FROM input('{_sql_path(source)}') f"

    assert cli.main([query]) == 0

    printed = capsys.readouterr().out
    assert "{(1,Intro,0.0,1.0),(2,Chapter 1,1.0,2.0)," in printed
    assert "(3,Chapter 2,2.0,3.0),(4,Credits,3.0,4.0)}" in printed
    assert "(1 row)" in printed


def test_a_written_chapters_column_is_read_back_off_the_output(
    tmp_path: Path,
) -> None:
    """The whole round trip: write chapter records, compile them into a real
    ffmetadata `-i`, run it, and read the titles and times back with ffprobe
    -- proving the extra input actually carries chapters, not just that the
    command has the right shape."""
    _require_fixture(_AV)
    out_path = tmp_path / "chaptered.mkv"
    query = (
        "COPY (\n"
        f"  SELECT f.video[1], f.audio[1],\n"
        "         ARRAY[ROW('Intro', 0, 1)::chapter,\n"
        "               ROW('Credits', 1, 2)::chapter] AS chapters\n"
        f"  FROM input('{_sql_path(_AV)}') f\n"
        f") TO '{_sql_path(out_path)}';"
    )

    _run_sink_query(query, out_path)

    chapters = _ffprobe_chapters(out_path)
    assert [c["tags"]["title"] for c in chapters] == ["Intro", "Credits"]
    assert [float(c["start_time"]) for c in chapters] == [0.0, 1.0]
    assert [float(c["end_time"]) for c in chapters] == [1.0, 2.0]


def test_a_gathered_chapters_column_writes_the_same_file(tmp_path: Path) -> None:
    """`array_agg` over a VALUES row source is the relational spelling of the
    same list, so the file it writes carries the same chapters."""
    _require_fixture(_AV)
    out_path = tmp_path / "gathered.mkv"
    query = (
        "COPY (\n"
        "  WITH marks(start_t, end_t, title) AS (\n"
        "    VALUES (0, 1, 'Intro'), (1, 2, 'Credits')\n"
        "  )\n"
        f"  SELECT f.video[1], f.audio[1],\n"
        "         array_agg(ROW(m.title, m.start_t, m.end_t)::chapter) AS chapters\n"
        f"  FROM input('{_sql_path(_AV)}') f, marks m\n"
        "  GROUP BY f.video[1], f.audio[1]\n"
        f") TO '{_sql_path(out_path)}';"
    )

    _run_sink_query(query, out_path)

    chapters = _ffprobe_chapters(out_path)
    assert [c["tags"]["title"] for c in chapters] == ["Intro", "Credits"]
    assert [float(c["start_time"]) for c in chapters] == [0.0, 1.0]


def test_a_copied_chapters_column_carries_an_inputs_own_list_through(
    tmp_path: Path,
) -> None:
    """`f.chapters AS chapters` needs no records at all: it just re-maps an
    existing input's chapters onto the output, unchanged."""
    _require_fixture(_FIXTURES_DIR / "av-chapters.mkv")
    source = _FIXTURES_DIR / "av-chapters.mkv"
    out_path = tmp_path / "recopied.mkv"
    query = (
        "COPY (SELECT f.video[1], f.audio[1], f.chapters AS chapters "
        f"FROM input('{_sql_path(source)}') f) "
        f"TO '{_sql_path(out_path)}';"
    )

    _run_sink_query(query, out_path)

    chapters = _ffprobe_chapters(out_path)
    assert [c["tags"]["title"] for c in chapters] == [
        "Intro",
        "Chapter 1",
        "Chapter 2",
        "Credits",
    ]


def test_a_null_chapters_column_writes_a_file_with_none(tmp_path: Path) -> None:
    """The clear, run for real: the source has four chapters and the output
    has none, which only `-map_chapters -1` produces."""
    source = _FIXTURES_DIR / "av-chapters.mkv"
    _require_fixture(source)
    out_path = tmp_path / "stripped.mkv"
    query = (
        "COPY (SELECT f.video[1], f.audio[1], NULL AS chapters "
        f"FROM input('{_sql_path(source)}') f) "
        f"TO '{_sql_path(out_path)}';"
    )

    _run_sink_query(query, out_path)

    assert _ffprobe_chapters(out_path) == []


# ---------------------------------------------------------------------------
# plan 078: disposition, metadata_from, amerge -- read back for real, not
# just checked for the right command shape (that part is the cookbook's job).
# ---------------------------------------------------------------------------


def test_disposition_column_flags_the_default_track(tmp_path: Path) -> None:
    """Cookbook recipe 41's query, run for real: ffprobe's own disposition
    block on the output proves `-disposition:<i>` actually reached the
    muxer, not just that the printed command has the right shape."""
    _require_fixture(_AV2)
    out_path = tmp_path / "flagged.mka"
    query = (
        "WITH flagged AS ("
        "  SELECT t AS track, "
        "  CASE WHEN t.tags.language = 'eng' THEN 'default' ELSE '0' END AS disposition "
        f"  FROM input('{_sql_path(_AV2)}') f, unnest(f.audio) t"
        ") SELECT array_agg(flagged.track) FROM flagged"
    )

    _compile_and_run(query, out_path)

    dispositions = _ffprobe_audio_dispositions(out_path)
    assert dispositions[0]["disposition"]["default"] == 1
    assert dispositions[1]["disposition"]["default"] == 0


def test_the_flag_set_is_the_one_this_ffmpeg_reports(tmp_path: Path) -> None:
    """The closed key set in types.py comes from ffprobe itself, so the local
    ffmpeg must still report exactly those keys and no others."""
    _require_fixture(_AV2)
    reported = _ffprobe_audio_dispositions(_AV2)[0]["disposition"]
    assert isinstance(reported, dict)
    assert tuple(reported) == DISPOSITION_KEYS


def test_a_written_multi_flag_spec_reaches_the_muxer(tmp_path: Path) -> None:
    """`'default+forced'` is ffmpeg's own spelling, and both flags land."""
    _require_fixture(_AV2)
    out_path = tmp_path / "both.mka"
    query = (
        "SELECT t, 'default+forced' AS disposition "
        f"FROM input('{_sql_path(_AV2)}') f, unnest(f.audio) t WHERE t.index = 2"
    )

    _compile_and_run(query, out_path)

    flags = _ffprobe_audio_dispositions(out_path)[0]["disposition"]
    assert isinstance(flags, dict)
    assert flags["default"] == 1
    assert flags["forced"] == 1


def test_a_flag_read_back_off_the_output_finds_the_track(tmp_path: Path) -> None:
    """The write and the read are the same map: flag a track, then pick it out
    of the written file by that flag."""
    _require_fixture(_AV2)
    out_path = tmp_path / "flagged.mka"
    query = (
        "WITH flagged AS ("
        "  SELECT t AS track, "
        "  CASE WHEN t.index = 2 THEN 'forced' ELSE '0' END AS disposition "
        f"  FROM input('{_sql_path(_AV2)}') f, unnest(f.audio) t"
        ") SELECT array_agg(flagged.track) FROM flagged"
    )
    _compile_and_run(query, out_path)

    sinks = lower_table(
        resolve(parse(
            f"SELECT t.index FROM input('{_sql_path(out_path)}') g, unnest(g.audio) t "
            "WHERE t.disposition.forced"
        )),
        {"g": probe(str(out_path))},
    )
    assert sinks[0].result.rows == [[2]]


def test_amerge_runs_and_produces_one_multichannel_stream(tmp_path: Path) -> None:
    """`amerge` is excluded from the registry's tables; N_INPUT is what makes
    it callable at all (mirrors the amix exec test), and running it for real
    proves the two mono tracks actually landed in one merged stream."""
    _require_fixture(_AV2)
    _require_fixture(_AV3)
    out_path = tmp_path / "merged.mka"
    query = (
        f"SELECT amerge(a.audio[1], b.audio[1]) "
        f"FROM input('{_sql_path(_AV2)}') a, input('{_sql_path(_AV3)}') b"
    )

    _compile_and_run(query, out_path)

    streams = _ffprobe_streams(out_path)
    assert len(streams) == 1
    assert streams[0]["codec_type"] == "audio"
    assert streams[0]["channels"] == 2  # two mono `sine` tracks merged


def _find_ladspa_plugin() -> Path | None:
    """The first loadable LADSPA plugin file this machine has, or None.

    Searches ``LADSPA_PATH`` (``;``-separated on Windows, ``:`` elsewhere,
    ffmpeg's own convention) plus ffmpeg's compiled-in default
    (``/usr/lib/ladspa`` on Linux builds; gyan's Windows builds carry no
    such default) for a ``.dll``/``.so``/``.dylib`` file. Best-effort: it
    proves a plugin FILE exists, not that it is a valid LADSPA plugin ffmpeg
    can load -- good enough to decide whether this exec test can run at all.
    """
    search_dirs = [
        Path(p) for p in os.environ.get("LADSPA_PATH", "").split(os.pathsep) if p
    ]
    search_dirs.append(Path("/usr/lib/ladspa"))
    for directory in search_dirs:
        if not directory.is_dir():
            continue
        for pattern in ("*.dll", "*.so", "*.dylib"):
            found = next(directory.glob(pattern), None)
            if found is not None:
                return found
    return None


def test_ladspa_runs_and_produces_one_audio_stream(tmp_path: Path) -> None:
    """`ladspa` joins the N_INPUT table with no count option -- ffmpeg derives
    its pad count from the plugin's own ports. Running it for real needs an
    actual LADSPA plugin FILE on this machine (`LADSPA_PATH`, or ffmpeg's
    compiled-in default); gyan's Windows ffmpeg builds carry no bundled
    plugins and this repo does not vendor one, so this test skips on a plain
    Windows checkout rather than fabricate a plugin path that would only
    ever fail at run time."""
    plugin_file = _find_ladspa_plugin()
    if plugin_file is None:
        pytest.skip(
            "no LADSPA plugin file found (checked $LADSPA_PATH and "
            "/usr/lib/ladspa) -- nothing for ladspa() to load on this machine"
        )
    _require_fixture(_AV2)
    out_path = tmp_path / "ladspa.mka"
    query = (
        f"SELECT ladspa(a.audio[1], file => '{plugin_file.stem}') "
        f"FROM input('{_sql_path(_AV2)}') a"
    )

    _compile_and_run(query, out_path)

    streams = _ffprobe_streams(out_path)
    assert len(streams) == 1
    assert streams[0]["codec_type"] == "audio"


def test_metadata_from_copies_an_inputs_global_tags_through(tmp_path: Path) -> None:
    """`metadata_from <alias>` round-trips a real input's container-level
    tags onto the output via ffprobe's format tags, not just the compiled
    command's shape (recipe 42, exec tier, only proves that offline)."""
    _require_fixture(_AV)
    tagged = tmp_path / "tagged.mkv"
    tag_args = [
        "ffmpeg",
        "-y",
        "-i",
        str(_AV),
        "-c",
        "copy",
        "-metadata",
        "genre=Test Genre",
        str(tagged),
    ]
    result = subprocess.run(
        tag_args, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT
    )
    assert result.returncode == 0, result.stderr

    out_path = tmp_path / "copied.mkv"
    query = (
        "COPY (SELECT f.video[1], f.audio[1] "
        f"FROM input('{_sql_path(tagged)}') f) "
        f"TO '{_sql_path(out_path)}' WITH (metadata_from f);"
    )

    _run_sink_query(query, out_path)

    # mkv's own convention uppercases tag keys (GENRE, not genre) -- lookup
    # case-insensitively, since it's the VALUE round-tripping that's under test.
    tags = {k.lower(): v for k, v in _ffprobe_format_tags(out_path).items()}
    assert tags.get("genre") == "Test Genre"


def test_container_tag_columns_round_trip_through_real_ffmpeg(tmp_path: Path) -> None:
    """Recipe 52 for real: read the input's tags, rewrite them, clear one.

    The fixture's `encoder` tag is written by the muxer and varies by ffmpeg
    version, so nothing here reads it.
    """
    _require_fixture(_TAGGED)
    out_path = tmp_path / "restored.mkv"
    query = (
        "COPY (SELECT f.video[1], f.audio[1], "
        "f.tags.title || ' (restored)' AS title, "
        "CASE WHEN f.tags.comment IS NULL THEN 'no notes' ELSE f.tags.comment END AS comment, "
        "NULL AS artist "
        f"FROM input('{_sql_path(_TAGGED)}') f) TO '{_sql_path(out_path)}';"
    )

    _run_sink_query(query, out_path)

    tags = {k.lower(): v for k, v in _ffprobe_format_tags(out_path).items()}
    assert tags.get("title") == "Angel One (restored)"
    assert tags.get("comment") == "no notes"
    assert not tags.get("artist")  # cleared: absent, or present and empty


# ---------------------------------------------------------------------------
# two-level tagging: the WITH tags the streams, the outer SELECT the file
# ---------------------------------------------------------------------------


def _ffprobe_stream_titles(path: Path) -> list[str | None]:
    """Each stream's `title` tag in file order, None where it has none."""
    args = [
        "ffprobe",
        "-v",
        "error",
        "-show_entries",
        "stream_tags=title",
        "-of",
        "json",
        str(path),
    ]
    result = subprocess.run(
        args, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT
    )
    assert result.returncode == 0, result.stderr
    data = json.loads(result.stdout)
    return [stream.get("tags", {}).get("title") for stream in data["streams"]]


def test_a_cte_tags_the_streams_while_the_outer_select_tags_the_file(
    tmp_path: Path,
) -> None:
    """Recipe 53 for real: both scopes written in one query, both read back off
    the written file."""
    _require_fixture(_AV2)
    out_path = tmp_path / "two-level.mkv"
    query = (
        "COPY ("
        "  WITH tagged AS ("
        "    SELECT a AS track, 'Audio (' || a.tags.language || ')' AS title"
        f"    FROM input('{_sql_path(_AV2)}') f, unnest(f.audio) a"
        "  )"
        "  SELECT g.video, array_agg(tagged.track), 'Director Cut' AS title"
        f"  FROM input('{_sql_path(_AV2)}') g, tagged GROUP BY g.video"
        f") TO '{_sql_path(out_path)}';"
    )

    _run_sink_query(query, out_path)

    assert _ffprobe_stream_titles(out_path) == [None, "Audio (eng)", "Audio (fra)"]
    tags = {k.lower(): v for k, v in _ffprobe_format_tags(out_path).items()}
    assert tags.get("title") == "Director Cut"


# ---------------------------------------------------------------------------
# two_pass: a compile that is a SEQUENCE of ffmpeg commands
# ---------------------------------------------------------------------------


def _run_command_sequence(commands: list[list[str]]) -> None:
    for command in commands:
        command.insert(1, "-y")
        result = subprocess.run(
            command, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT
        )
        assert result.returncode == 0, f"{command}\n{result.stderr}"


def test_two_pass_encode_runs_both_passes_and_writes_a_playable_file(
    tmp_path: Path,
) -> None:
    """The whole chain against real ffmpeg: pass 1 writes only ffmpeg's stats
    file, pass 2 reads it and writes the destination.

    The stats file is ffmpeg's own temp file and is deliberately NOT cleaned
    up: it stays beside the destination as `<dest>-0.log` (plus x264's
    `-0.log.mbtree`), which this asserts rather than works around.
    """
    _require_fixture(_AV)
    out_path = tmp_path / "two-pass.mp4"
    query = (
        "COPY (\n"
        f"  SELECT f.video[1], f.audio[1] FROM input('{_sql_path(_AV)}') f\n"
        f") TO '{_sql_path(out_path)}' WITH (\n"
        "  video_codec 'libx264', video_bitrate '500k', two_pass true, "
        "audio_codec 'aac'\n"
        ")"
    )

    commands = build_ffmpeg_commands(emit(compile_sql(query)))
    assert len(commands) == 2
    assert commands[0][-3:] == ["-f", "null", "-"]
    assert commands[0][commands[0].index("-pass") + 1] == "1"
    assert commands[1][commands[1].index("-pass") + 1] == "2"
    logfile = commands[0][commands[0].index("-passlogfile") + 1]
    assert logfile == _sql_path(out_path)

    # Pass 1 alone: the stats file appears beside the destination, and the
    # destination itself is not written.
    _run_command_sequence([commands[0]])
    stats = Path(f"{logfile}-0.log")
    assert stats.exists()
    assert not out_path.exists()

    _run_command_sequence([commands[1]])

    assert out_path.exists()
    assert stats.exists()  # ffmpeg owns its temp files; sqlmpeg leaves them
    streams = _ffprobe_streams(out_path)
    assert [s["codec_type"] for s in streams] == ["video", "audio"]
    assert streams[0]["codec_name"] == "h264"
    assert streams[1]["codec_name"] == "aac"
    assert _ffprobe_duration(out_path) == pytest.approx(
        _ffprobe_duration(_AV), abs=0.3
    )


def test_two_pass_keeps_a_filtered_audio_pad_connected_in_pass_one(
    tmp_path: Path,
) -> None:
    """A FILTERED audio output stays mapped in pass 1: ffmpeg refuses a
    filtergraph output pad with no consumer, so dropping it would break the
    analysis pass outright."""
    _require_fixture(_AV)
    out_path = tmp_path / "two-pass-filtered.mp4"
    query = (
        "COPY (\n"
        f"  SELECT hflip(f.video[1]), volume(f.audio[1], 0.5)\n"
        f"  FROM input('{_sql_path(_AV)}') f\n"
        f") TO '{_sql_path(out_path)}' WITH (\n"
        "  video_codec 'libx264', video_bitrate '500k', two_pass true, "
        "audio_codec 'aac'\n"
        ")"
    )

    commands = build_ffmpeg_commands(emit(compile_sql(query)))
    assert [c for i, c in enumerate(commands[0]) if commands[0][i - 1] == "-map"] == [
        "[out0]",
        "[out1]",
    ]

    _run_command_sequence(commands)

    assert out_path.exists()
    assert [s["codec_type"] for s in _ffprobe_streams(out_path)] == ["video", "audio"]


def test_two_pass_runs_end_to_end_through_the_cli(tmp_path: Path) -> None:
    """`sqlmpeg run` drives the sequence itself: one process, both passes."""
    _require_fixture(_AV)
    out_path = tmp_path / "cli-two-pass.mp4"
    query = (
        "COPY (\n"
        f"  SELECT f.video[1], f.audio[1] FROM input('{_sql_path(_AV)}') f\n"
        f") TO '{_sql_path(out_path)}' WITH (\n"
        "  video_codec 'libx264', video_bitrate '500k', two_pass true\n"
        ")"
    )

    assert cli.main(["run", query, "-y"]) == 0

    assert out_path.exists()
    assert Path(f"{_sql_path(out_path)}-0.log").exists()
    assert [s["codec_type"] for s in _ffprobe_streams(out_path)] == ["video", "audio"]


# ---------------------------------------------------------------------------
# two-pass loudnorm: measure, substitute, encode -- then measure the result
# ---------------------------------------------------------------------------

_LOUDNORM_TARGET_I = -16.0
# EBU R128 tolerance for this check: the whole point of measuring first is
# that the delivered file lands on target, not near it.
_LOUDNORM_TOLERANCE_LU = 1.0


def _measure_loudness(path: Path) -> dict[str, str]:
    """`path`'s integrated loudness, measured by a fresh loudnorm pass."""
    args = [
        "ffmpeg",
        "-hide_banner",
        "-i",
        str(path),
        "-filter_complex",
        "[0:a:0]loudnorm=print_format=json[out0]",
        "-map",
        "[out0]",
        "-f",
        "null",
        "-",
    ]
    result = subprocess.run(
        args, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT
    )
    assert result.returncode == 0, result.stderr
    return loudnorm.parse(result.stderr)


def _loudnorm2_query(source: Path, out_path: Path) -> str:
    return (
        "COPY (\n"
        "  SELECT sqlmpeg.loudnorm2(f.audio[1], I => -16, TP => -1.5, LRA => 11)\n"
        f"  FROM input('{_sql_path(source)}') f\n"
        f") TO '{_sql_path(out_path)}' WITH (audio_codec 'aac')"
    )


def test_loudnorm2_run_lands_on_target(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """`run` does the whole handoff in process: measure, parse, substitute,
    encode. The delivered file's own measured loudness is the assertion."""
    _require_fixture(_AV)
    out_path = tmp_path / "loudnorm2.m4a"

    assert cli.main(["run", _loudnorm2_query(_AV, out_path), "-y"]) == 0
    printed = capsys.readouterr().out

    # The second command really carries numbers, not variable references.
    assert "${SQLMPEG_LN_" not in printed
    assert "measured_I=" in printed

    measured = _measure_loudness(out_path)
    delivered = float(measured["SQLMPEG_LN_I"])
    assert abs(delivered - _LOUDNORM_TARGET_I) <= _LOUDNORM_TOLERANCE_LU, measured
    assert float(measured["SQLMPEG_LN_TP"]) <= -1.5


def test_loudnorm2_measuring_pass_writes_nothing(tmp_path: Path) -> None:
    """Pass 1 measures and muxes to `-f null -`; the destination only appears
    once the correction pass has run."""
    _require_fixture(_AV)
    out_path = tmp_path / "not-yet.m4a"
    commands = build_ffmpeg_commands(emit(compile_sql(_loudnorm2_query(_AV, out_path))))

    _run_command_sequence([commands[0]])

    assert not out_path.exists()


def test_loudnorm2_measurements_reach_the_correction_pass(tmp_path: Path) -> None:
    """The library seam, without the CLI: run pass 1, parse its stderr with
    the shared parser, substitute into pass 2's argv, run that."""
    _require_fixture(_AV)
    out_path = tmp_path / "spliced.m4a"
    measure, correct = build_ffmpeg_commands(
        emit(compile_sql(_loudnorm2_query(_AV, out_path)))
    )

    result = subprocess.run(
        measure, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT
    )
    assert result.returncode == 0, result.stderr
    values = loudnorm.parse(result.stderr)

    substituted = [loudnorm.substitute(word, values) for word in correct]
    assert substituted != correct
    _run_command_sequence([substituted])

    assert out_path.exists()
    delivered = float(_measure_loudness(out_path)["SQLMPEG_LN_I"])
    assert abs(delivered - _LOUDNORM_TARGET_I) <= _LOUDNORM_TOLERANCE_LU


def test_the_printed_loudnorm2_command_runs_in_bash(tmp_path: Path) -> None:
    """The printed line is a POSIX-shell chain, and this is the only test that
    proves it: `eval "$(... | sqlmpeg loudnorm2env)"` exporting into the
    second command's environment, spliced back through adjacent quotes.

    Skipped where there is no bash (the printed form is POSIX-only by design;
    cmd.exe/PowerShell users have `run`) and where the `sqlmpeg` console
    script is not installed, since the chain calls it by name. When it is
    installed but the environment was never activated, its directory is put
    on PATH for the shell -- which is what activating would have done.
    """
    # System32's bash.exe is the WSL shim, which hangs when no distro is
    # ready; prefer a real bash (Git Bash on Windows) and prove it answers.
    candidates = [
        shutil.which("bash"),
        r"C:\Program Files\Git\usr\bin\bash.exe",
        r"C:\Program Files\Git\bin\bash.exe",
    ]
    bash = None
    for candidate in candidates:
        if not candidate or not Path(candidate).exists():
            continue
        if "system32" in candidate.lower():
            continue
        try:
            probe = subprocess.run(
                [candidate, "-c", "echo ok"], capture_output=True, text=True, timeout=10
            )
        except (OSError, subprocess.SubprocessError):
            continue
        if probe.returncode == 0 and probe.stdout.strip() == "ok":
            bash = candidate
            break
    if bash is None:
        pytest.skip("no working non-WSL bash found (the printed chain is POSIX-shell only)")
    console_script = shutil.which("sqlmpeg") or shutil.which(
        "sqlmpeg", path=str(Path(sys.executable).parent)
    )
    if console_script is None:
        pytest.skip("the sqlmpeg console script is not installed")
    env = dict(
        os.environ,
        PATH=str(Path(console_script).parent) + os.pathsep + os.environ["PATH"],
    )
    _require_fixture(_AV)
    out_path = tmp_path / "bash.m4a"

    printed = subprocess.run(
        [sys.executable, "-m", "sqlmpeg", "compile", _loudnorm2_query(_AV, out_path)],
        capture_output=True,
        text=True,
        timeout=_SUBPROCESS_TIMEOUT,
    )
    assert printed.returncode == 0, printed.stderr
    line = printed.stdout.strip()

    result = subprocess.run(
        [bash, "-c", f"set -e\n{line}"],
        capture_output=True,
        text=True,
        timeout=_SUBPROCESS_TIMEOUT,
        env=env,
    )
    assert result.returncode == 0, result.stderr
    assert out_path.exists()
    delivered = float(_measure_loudness(out_path)["SQLMPEG_LN_I"])
    assert abs(delivered - _LOUDNORM_TARGET_I) <= _LOUDNORM_TOLERANCE_LU


# ---------------------------------------------------------------------------
# compile-time arithmetic: per-row filter arguments and duration trim bounds
# ---------------------------------------------------------------------------


def test_a_per_row_scale_argument_runs_against_the_real_probe(tmp_path: Path) -> None:
    """Recipe 45: each rendition is scaled against its OWN probed width, so
    the emitted number comes from the file rather than from the query."""
    _require_fixture(_AV2)
    out_path = tmp_path / "half.mp4"
    query = (
        "SELECT scale(t, t.width / 2, -2) "
        f"FROM input('{_sql_path(_AV2)}') f, unnest(f.video) t"
    )

    source = _ffprobe_video_stream(_AV2)
    _compile_and_run(query, out_path)

    assert _ffprobe_video_stream(out_path)["width"] == int(source["width"]) // 2  # type: ignore[call-overload]


def test_a_duration_trim_bound_shortens_the_output(tmp_path: Path) -> None:
    """Recipe 46: `f.duration - 0.5` needs no known length, and the file that
    comes out really is shorter than the one that went in."""
    _require_fixture(_AV2)
    out_path = tmp_path / "trimmed.mp4"
    query = (
        f"SELECT f.video[1], f.audio[1] FROM input('{_sql_path(_AV2)}') f "
        "WHERE f.t <= f.duration - 0.5"
    )

    source_duration = _ffprobe_duration(_AV2)
    _compile_and_run(query, out_path)

    assert _ffprobe_duration(out_path) < source_duration
