"""End-to-end exec tests: compile sqlmpeg queries and run them through real
ffmpeg against synthetic fixtures generated by ``scripts/gen_fixtures.py``.

Marked ``@pytest.mark.exec`` (registered in ``pyproject.toml``); excluded
from the default test run via ``addopts = -m "not exec"``. Run explicitly::

    python -m pytest -m exec tests/exec -q

Requires ``ffmpeg``/``ffprobe`` on PATH and the fixtures already generated
(``python scripts/gen_fixtures.py``). Tests skip cleanly if either is
missing, per plan 010.
"""

from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path

import imagehash
import pytest
from PIL import Image

from sqlmpeg.compiler import compile_sql
from sqlmpeg.emit import build_ffmpeg_args, emit

pytestmark = pytest.mark.exec

_FIXTURES_DIR = Path(__file__).resolve().parent.parent / "fixtures"
_TESTSRC = _FIXTURES_DIR / "testsrc.mp4"
_AV2 = _FIXTURES_DIR / "av2.mp4"
_AV3 = _FIXTURES_DIR / "av3.mp4"
# RFC-004 caption fixtures: avs.mkv is video + audio + an srt track tagged
# language=eng; subs.en.vtt is a standalone 3-cue WebVTT file (no tags).
_AVS = _FIXTURES_DIR / "avs.mkv"
_SUBS_VTT = _FIXTURES_DIR / "subs.en.vtt"

_SRC_WIDTH = 320
_SRC_HEIGHT = 240

_SUBPROCESS_TIMEOUT = 60.0
_PHASH_MAX_DISTANCE = 8


# ---------------------------------------------------------------------------
# skip / helper plumbing
# ---------------------------------------------------------------------------


def _require_fixture(path: Path) -> None:
    if not path.exists():
        pytest.skip(f"fixture missing: {path} (run scripts/gen_fixtures.py first)")


@pytest.fixture(autouse=True)
def _require_ffmpeg_tools() -> None:
    if shutil.which("ffmpeg") is None or shutil.which("ffprobe") is None:
        pytest.skip("ffmpeg/ffprobe not found on PATH")


def _sql_path(path: Path) -> str:
    """Render `path` as the body of a SQL string literal.

    Forward slashes even on Windows: ffmpeg accepts them, and it sidesteps
    backslash-escaping inside the SQL string literal entirely.
    """
    return path.resolve().as_posix()


def _compile_and_run(query: str, out_path: Path) -> None:
    graph = compile_sql(query)
    emitted = emit(graph)
    args = build_ffmpeg_args(emitted, str(out_path))
    args.insert(1, "-y")
    result = subprocess.run(
        args, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT
    )
    assert result.returncode == 0, result.stderr
    assert out_path.exists()


def _ffprobe_video_stream(path: Path) -> dict[str, object]:
    args = [
        "ffprobe",
        "-v",
        "error",
        "-select_streams",
        "v:0",
        "-show_entries",
        "stream=width,height",
        "-of",
        "json",
        str(path),
    ]
    result = subprocess.run(
        args, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT
    )
    assert result.returncode == 0, result.stderr
    data = json.loads(result.stdout)
    streams = data["streams"]
    assert streams, f"no video stream found in {path}"
    stream: dict[str, object] = streams[0]
    return stream


def _ffprobe_duration(path: Path) -> float:
    args = [
        "ffprobe",
        "-v",
        "error",
        "-show_entries",
        "format=duration",
        "-of",
        "json",
        str(path),
    ]
    result = subprocess.run(
        args, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT
    )
    assert result.returncode == 0, result.stderr
    data = json.loads(result.stdout)
    return float(data["format"]["duration"])


def _ffprobe_streams(path: Path) -> list[dict[str, object]]:
    args = [
        "ffprobe",
        "-v",
        "error",
        "-show_entries",
        "stream=index,codec_type,codec_name",
        "-show_entries",
        "stream_tags=language",
        "-of",
        "json",
        str(path),
    ]
    result = subprocess.run(
        args, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT
    )
    assert result.returncode == 0, result.stderr
    data = json.loads(result.stdout)
    streams: list[dict[str, object]] = data["streams"]
    return streams


def _extract_frame(video: Path, t: float, out_png: Path) -> None:
    args = [
        "ffmpeg",
        "-y",
        "-ss",
        str(t),
        "-i",
        str(video),
        "-frames:v",
        "1",
        str(out_png),
    ]
    result = subprocess.run(
        args, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT
    )
    assert result.returncode == 0, result.stderr
    assert out_png.exists()


# ---------------------------------------------------------------------------
# tests
# ---------------------------------------------------------------------------


def test_scale_reports_expected_dimensions(tmp_path: Path) -> None:
    _require_fixture(_TESTSRC)
    out_path = tmp_path / "scaled.mp4"
    query = f"SELECT scale(a.frame, 0.5) FROM input('{_sql_path(_TESTSRC)}') a"

    _compile_and_run(query, out_path)

    stream = _ffprobe_video_stream(out_path)
    assert stream["width"] == _SRC_WIDTH // 2
    assert stream["height"] == _SRC_HEIGHT // 2


def test_trim_reports_expected_duration(tmp_path: Path) -> None:
    _require_fixture(_TESTSRC)
    out_path = tmp_path / "trimmed.mp4"
    query = (
        f"SELECT a.frame FROM input('{_sql_path(_TESTSRC)}') a "
        "WHERE a.t BETWEEN 0 AND 1"
    )

    _compile_and_run(query, out_path)

    duration = _ffprobe_duration(out_path)
    assert duration == pytest.approx(1.0, abs=0.2)


def test_hflip_matches_pil_flipped_source_by_phash(tmp_path: Path) -> None:
    _require_fixture(_TESTSRC)
    out_path = tmp_path / "hflipped.mp4"
    query = f"SELECT hflip(a.frame) FROM input('{_sql_path(_TESTSRC)}') a"

    _compile_and_run(query, out_path)

    source_png = tmp_path / "source_frame.png"
    output_png = tmp_path / "output_frame.png"
    _extract_frame(_TESTSRC, 1.0, source_png)
    _extract_frame(out_path, 1.0, output_png)

    with Image.open(source_png) as source_img:
        expected = source_img.transpose(Image.Transpose.FLIP_LEFT_RIGHT)
        expected_hash = imagehash.phash(expected)
    with Image.open(output_png) as output_img:
        actual_hash = imagehash.phash(output_img)

    distance = expected_hash - actual_hash
    assert distance <= _PHASH_MAX_DISTANCE


# ---------------------------------------------------------------------------
# multi-stream (v2 / RFC-001): remap-only passthrough and audio broadcasting
# ---------------------------------------------------------------------------


def test_remap_only_stream_copies_the_selected_audio_track(tmp_path: Path) -> None:
    """`a.video[1], a.audio[2]` on a 2-audio-track file: nothing re-encoded.

    av2.mp4 tags its second audio track `language=fra`; a bare subscript with
    zero node consumers must stay a passthrough (-map + -c copy), so the
    output keeps that tag and the exact input codec.
    """
    _require_fixture(_AV2)
    out_path = tmp_path / "remap.mp4"
    query = f"SELECT a.video[1], a.audio[2] FROM input('{_sql_path(_AV2)}') a"

    graph = compile_sql(query)
    emitted = emit(graph)
    assert emitted.filter_complex == ""  # pure passthrough: no filtergraph at all

    args = build_ffmpeg_args(emitted, str(out_path))
    assert "-c:0" in args and "-c:1" in args  # both outputs are stream-copied
    args.insert(1, "-y")
    result = subprocess.run(args, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT)
    assert result.returncode == 0, result.stderr
    assert out_path.exists()

    streams = _ffprobe_streams(out_path)
    assert [s["codec_type"] for s in streams] == ["video", "audio"]
    audio = streams[1]
    assert audio["tags"]["language"] == "fra"
    source_audio = _ffprobe_streams(_AV2)[2]  # a.audio[2] is the fra track (1-based)
    assert audio["codec_name"] == source_audio["codec_name"]


def test_reverb_broadcast_produces_a_tagged_stream_per_language_track(tmp_path: Path) -> None:
    """`reverb(a.audio, 0.3)` on a 2-audio-track file expands to two aecho
    subgraphs, one per track, and each output keeps its source language tag."""
    _require_fixture(_AV2)
    out_path = tmp_path / "reverb.mp4"
    query = f"SELECT reverb(a.audio, 0.3) FROM input('{_sql_path(_AV2)}') a"

    _compile_and_run(query, out_path)

    streams = _ffprobe_streams(out_path)
    assert [s["codec_type"] for s in streams] == ["audio", "audio"]
    assert [s["tags"]["language"] for s in streams] == ["eng", "fra"]


# ---------------------------------------------------------------------------
# UNION ALL splat: concat two dual-language sources, tracks paired by position
# ---------------------------------------------------------------------------


def test_union_splat_concatenates_both_language_tracks(tmp_path: Path) -> None:
    """The README headline, end to end.

    Both branches splat `<alias>.audio`, so UNION ALL's column matching pairs
    av2's and av3's tracks elementwise into `concat=n=2:v=1:a=2`. The two files
    tag their tracks eng/fra alike, so both concat audio pads keep the language
    they agree on -- and the run is twice as long as either source.
    """
    _require_fixture(_AV2)
    _require_fixture(_AV3)
    out_path = tmp_path / "season.mp4"
    query = (
        f"SELECT a.frame, a.audio FROM input('{_sql_path(_AV2)}') a "
        f"UNION ALL "
        f"SELECT b.frame, b.audio FROM input('{_sql_path(_AV3)}') b"
    )

    _compile_and_run(query, out_path)

    streams = _ffprobe_streams(out_path)
    assert [s["codec_type"] for s in streams] == ["video", "audio", "audio"]
    assert [s["tags"]["language"] for s in streams[1:]] == ["eng", "fra"]
    assert _ffprobe_duration(out_path) == pytest.approx(
        _ffprobe_duration(_AV2) + _ffprobe_duration(_AV3), abs=0.3
    )


# ---------------------------------------------------------------------------
# PiP composite + broadcast-zip mix: the plan 024 flagship, end to end
# ---------------------------------------------------------------------------


def test_pip_mix_flagship_composites_video_and_keeps_both_language_tags(
    tmp_path: Path,
) -> None:
    """The README headline, end to end.

    `pip` scales commentary down and `overlay`s it onto the film; `volume`
    broadcasts over each file's 2-track audio array and `amix` zips the pairs,
    English with English and French with French. The composited video output
    stays the base film's size (the PiP shrinks, not the frame it lands on);
    both mixed audio outputs keep the language both zipped sides agree on.
    """
    _require_fixture(_AV2)
    _require_fixture(_AV3)
    out_path = tmp_path / "pip.mp4"
    query = (
        "WITH pip AS ("
        f"  SELECT scale(c.frame, 0.25) AS frame, c.audio AS sound "
        f"  FROM input('{_sql_path(_AV3)}') c"
        ") "
        "SELECT overlay(f.frame, pip.frame, 20, 20), "
        "       amix(volume(f.audio, 0.65), volume(pip.sound, 0.35)) "
        f"FROM input('{_sql_path(_AV2)}') f, pip"
    )

    _compile_and_run(query, out_path)

    streams = _ffprobe_streams(out_path)
    assert [s["codec_type"] for s in streams] == ["video", "audio", "audio"]
    assert [s.get("tags", {}).get("language") for s in streams[1:]] == ["eng", "fra"]

    video = _ffprobe_video_stream(out_path)
    assert (video["width"], video["height"]) == (_SRC_WIDTH, _SRC_HEIGHT)


# ---------------------------------------------------------------------------
# COPY ... TO ... WITH (...) sink options: end to end (RFC-002, plan 028)
# ---------------------------------------------------------------------------


def test_copy_sink_codec_options_land_in_the_real_encode(tmp_path: Path) -> None:
    """Wrap the union-splat headline in a COPY and check the WITH (...) codec
    options actually reach ffmpeg, not just that the sink dict was built.

    The query concatenates av2 and av3 (splatting each file's whole audio
    array, same as the README headline) and asks for libx264/aac re-encodes
    at explicit bitrates; the sink's own TO path (not `-o`) is what
    `build_ffmpeg_args` resolves, and ffprobe on the real output confirms the
    video and both audio streams were actually re-encoded to the requested
    codecs.
    """
    _require_fixture(_AV2)
    _require_fixture(_AV3)
    out_path = tmp_path / "sink.mkv"
    query = (
        "COPY (\n"
        f"  SELECT a.frame, a.audio FROM input('{_sql_path(_AV2)}') a\n"
        "  UNION ALL\n"
        f"  SELECT b.frame, b.audio FROM input('{_sql_path(_AV3)}') b\n"
        f") TO '{_sql_path(out_path)}' WITH (\n"
        "  video_codec 'libx264', crf 28, audio_codec 'aac', audio_bitrate '96k'\n"
        ")"
    )

    graph = compile_sql(query)
    emitted = emit(graph)
    args = build_ffmpeg_args(emitted)  # no -o override: the sink's own path is used
    args.insert(1, "-y")
    result = subprocess.run(args, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT)
    assert result.returncode == 0, result.stderr
    assert out_path.exists()

    streams = _ffprobe_streams(out_path)
    assert [s["codec_type"] for s in streams] == ["video", "audio", "audio"]
    assert streams[0]["codec_name"] == "h264"
    assert streams[1]["codec_name"] == "aac"
    assert streams[2]["codec_name"] == "aac"


# ---------------------------------------------------------------------------
# RFC-004: SELECT *, subtitle streams, external caption joins (plan 034)
# ---------------------------------------------------------------------------


def _run_sink_query(query: str, out_path: Path) -> None:
    """Compile a COPY query and run it at ITS OWN sink path (no -o override)."""
    emitted = emit(compile_sql(query))
    args = build_ffmpeg_args(emitted)
    args.insert(1, "-y")
    result = subprocess.run(
        args, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT
    )
    assert result.returncode == 0, f"{args}\n{result.stderr}"
    assert out_path.exists()


def test_select_star_remuxes_every_stream_of_a_captioned_file(tmp_path: Path) -> None:
    """`SELECT *` over avs.mkv: video + audio + the eng-tagged subtitle track,
    all passthrough (no filtergraph at all), language tag carried through."""
    _require_fixture(_AVS)
    out_path = tmp_path / "star.mkv"
    query = f"SELECT * FROM input('{_sql_path(_AVS)}') a"

    emitted = emit(compile_sql(query))
    assert emitted.filter_complex == ""  # a star is a pure remux
    assert [m.target for m in emitted.maps] == ["0:v:0", "0:a:0", "0:s:0"]

    _compile_and_run(query, out_path)

    streams = _ffprobe_streams(out_path)
    assert [s["codec_type"] for s in streams] == ["video", "audio", "subtitle"]
    assert streams[2]["tags"]["language"] == "eng"


def test_qualified_star_mixes_with_an_explicit_column(tmp_path: Path) -> None:
    """`SELECT a.*, b.audio[1]`: one alias splatted whole, one column picked."""
    _require_fixture(_AVS)
    _require_fixture(_AV2)
    out_path = tmp_path / "star-mixed.mkv"
    query = (
        f"SELECT a.*, b.audio[1] "
        f"FROM input('{_sql_path(_AVS)}') a, input('{_sql_path(_AV2)}') b"
    )

    _compile_and_run(query, out_path)

    streams = _ffprobe_streams(out_path)
    assert [s["codec_type"] for s in streams] == [
        "video",
        "audio",
        "subtitle",
        "audio",
    ]
    assert streams[2]["tags"]["language"] == "eng"
    assert streams[3]["tags"]["language"] == "eng"  # av2's first track


def test_vtt_join_muxes_an_external_caption_track_into_an_mkv(tmp_path: Path) -> None:
    """RFC-004's headline: an external WebVTT file joined as a subtitle track.

    Two inputs, three columns, no new join semantics -- the SELECT list IS the
    -map list, and `subtitle_codec 'srt'` transcodes webvtt into the mkv.
    """
    _require_fixture(_AVS)
    _require_fixture(_SUBS_VTT)
    out_path = tmp_path / "joined.mkv"
    query = (
        "COPY (\n"
        f"  SELECT f.video[1], f.audio[1], s.subtitle[1]\n"
        f"  FROM input('{_sql_path(_AVS)}') f, input('{_sql_path(_SUBS_VTT)}') s\n"
        f") TO '{_sql_path(out_path)}' WITH (subtitle_codec 'srt')"
    )

    _run_sink_query(query, out_path)

    streams = _ffprobe_streams(out_path)
    assert [s["codec_type"] for s in streams] == ["video", "audio", "subtitle"]
    assert streams[2]["codec_name"] == "subrip"
    # The .vtt fixture carries no language tag of its own, and provenance never
    # invents one: the joined caption track is untagged.
    assert "language" not in streams[2].get("tags", {})


def test_vtt_join_transcodes_to_mov_text_in_an_mp4(tmp_path: Path) -> None:
    """The same join into an mp4, where mov_text is the only legal caption codec."""
    _require_fixture(_AVS)
    _require_fixture(_SUBS_VTT)
    out_path = tmp_path / "joined.mp4"
    query = (
        "COPY (\n"
        f"  SELECT f.video[1], f.audio[1], s.subtitle[1]\n"
        f"  FROM input('{_sql_path(_AVS)}') f, input('{_sql_path(_SUBS_VTT)}') s\n"
        f") TO '{_sql_path(out_path)}' WITH (subtitle_codec 'mov_text')"
    )

    _run_sink_query(query, out_path)

    streams = _ffprobe_streams(out_path)
    assert [s["codec_type"] for s in streams] == ["video", "audio", "subtitle"]
    assert streams[2]["codec_name"] == "mov_text"


def test_subtitle_extraction_writes_a_parseable_srt_file(tmp_path: Path) -> None:
    """`COPY (SELECT f.subtitle[1]) TO 'x.srt'` -- extraction falls out of sinks."""
    _require_fixture(_AVS)
    out_path = tmp_path / "captions.srt"
    query = (
        "COPY (\n"
        f"  SELECT f.subtitle[1] FROM input('{_sql_path(_AVS)}') f\n"
        f") TO '{_sql_path(out_path)}'"
    )

    _run_sink_query(query, out_path)

    text = out_path.read_text(encoding="utf-8")
    # SubRip: numbered cues with `hh:mm:ss,mmm --> hh:mm:ss,mmm` timings.
    assert text.lstrip().startswith("1\n") or text.lstrip().startswith("1\r\n")
    assert " --> " in text
    assert "Cue one." in text
    # ffprobe agrees it is a subtitle stream, i.e. the file really parses.
    streams = _ffprobe_streams(out_path)
    assert [s["codec_type"] for s in streams] == ["subtitle"]


def test_the_same_subtitle_track_may_be_mapped_twice(tmp_path: Path) -> None:
    """Duplicate consumption of one subtitle src ref: two Outputs, two identical
    bare -maps, no split filter anywhere (RFC-004's split/emit exemption)."""
    _require_fixture(_AVS)
    out_path = tmp_path / "twice.mkv"
    query = (
        f"SELECT a.video[1], a.subtitle[1], a.subtitle[1] "
        f"FROM input('{_sql_path(_AVS)}') a"
    )

    emitted = emit(compile_sql(query))
    assert emitted.filter_complex == ""
    assert [m.target for m in emitted.maps] == ["0:v:0", "0:s:0", "0:s:0"]

    _compile_and_run(query, out_path)

    streams = _ffprobe_streams(out_path)
    assert [s["codec_type"] for s in streams] == ["video", "subtitle", "subtitle"]
    assert [s["tags"]["language"] for s in streams[1:]] == ["eng", "eng"]
