"""End-to-end exec tests: compile sqlmpeg queries and run them through real
ffmpeg against synthetic fixtures generated by ``scripts/gen_fixtures.py``.

Marked ``@pytest.mark.exec`` (registered in ``pyproject.toml``); excluded
from the default test run via ``addopts = -m "not exec"``. Run explicitly::

    python -m pytest -m exec tests/exec -q

Requires ``ffmpeg``/``ffprobe`` on PATH and the fixtures already generated
(``python scripts/gen_fixtures.py``). Tests skip cleanly if either is
missing, per plan 010.
"""

from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path

import imagehash
import pytest
from PIL import Image

from sqlmpeg.compiler import compile_sql
from sqlmpeg.emit import build_ffmpeg_args, emit

pytestmark = pytest.mark.exec

_FIXTURES_DIR = Path(__file__).resolve().parent.parent / "fixtures"
_TESTSRC = _FIXTURES_DIR / "testsrc.mp4"
_AV2 = _FIXTURES_DIR / "av2.mp4"
_AV3 = _FIXTURES_DIR / "av3.mp4"

_SRC_WIDTH = 320
_SRC_HEIGHT = 240

_SUBPROCESS_TIMEOUT = 60.0
_PHASH_MAX_DISTANCE = 8


# ---------------------------------------------------------------------------
# skip / helper plumbing
# ---------------------------------------------------------------------------


def _require_fixture(path: Path) -> None:
    if not path.exists():
        pytest.skip(f"fixture missing: {path} (run scripts/gen_fixtures.py first)")


@pytest.fixture(autouse=True)
def _require_ffmpeg_tools() -> None:
    if shutil.which("ffmpeg") is None or shutil.which("ffprobe") is None:
        pytest.skip("ffmpeg/ffprobe not found on PATH")


def _sql_path(path: Path) -> str:
    """Render `path` as the body of a SQL string literal.

    Forward slashes even on Windows: ffmpeg accepts them, and it sidesteps
    backslash-escaping inside the SQL string literal entirely.
    """
    return path.resolve().as_posix()


def _compile_and_run(query: str, out_path: Path) -> None:
    graph = compile_sql(query)
    emitted = emit(graph)
    args = build_ffmpeg_args(emitted, str(out_path))
    args.insert(1, "-y")
    result = subprocess.run(
        args, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT
    )
    assert result.returncode == 0, result.stderr
    assert out_path.exists()


def _ffprobe_video_stream(path: Path) -> dict[str, object]:
    args = [
        "ffprobe",
        "-v",
        "error",
        "-select_streams",
        "v:0",
        "-show_entries",
        "stream=width,height",
        "-of",
        "json",
        str(path),
    ]
    result = subprocess.run(
        args, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT
    )
    assert result.returncode == 0, result.stderr
    data = json.loads(result.stdout)
    streams = data["streams"]
    assert streams, f"no video stream found in {path}"
    stream: dict[str, object] = streams[0]
    return stream


def _ffprobe_duration(path: Path) -> float:
    args = [
        "ffprobe",
        "-v",
        "error",
        "-show_entries",
        "format=duration",
        "-of",
        "json",
        str(path),
    ]
    result = subprocess.run(
        args, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT
    )
    assert result.returncode == 0, result.stderr
    data = json.loads(result.stdout)
    return float(data["format"]["duration"])


def _ffprobe_streams(path: Path) -> list[dict[str, object]]:
    args = [
        "ffprobe",
        "-v",
        "error",
        "-show_entries",
        "stream=index,codec_type,codec_name",
        "-show_entries",
        "stream_tags=language",
        "-of",
        "json",
        str(path),
    ]
    result = subprocess.run(
        args, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT
    )
    assert result.returncode == 0, result.stderr
    data = json.loads(result.stdout)
    streams: list[dict[str, object]] = data["streams"]
    return streams


def _extract_frame(video: Path, t: float, out_png: Path) -> None:
    args = [
        "ffmpeg",
        "-y",
        "-ss",
        str(t),
        "-i",
        str(video),
        "-frames:v",
        "1",
        str(out_png),
    ]
    result = subprocess.run(
        args, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT
    )
    assert result.returncode == 0, result.stderr
    assert out_png.exists()


# ---------------------------------------------------------------------------
# tests
# ---------------------------------------------------------------------------


def test_scale_reports_expected_dimensions(tmp_path: Path) -> None:
    _require_fixture(_TESTSRC)
    out_path = tmp_path / "scaled.mp4"
    query = f"SELECT scale(a.frame, 0.5) FROM input('{_sql_path(_TESTSRC)}') a"

    _compile_and_run(query, out_path)

    stream = _ffprobe_video_stream(out_path)
    assert stream["width"] == _SRC_WIDTH // 2
    assert stream["height"] == _SRC_HEIGHT // 2


def test_trim_reports_expected_duration(tmp_path: Path) -> None:
    _require_fixture(_TESTSRC)
    out_path = tmp_path / "trimmed.mp4"
    query = (
        f"SELECT a.frame FROM input('{_sql_path(_TESTSRC)}') a "
        "WHERE a.t BETWEEN 0 AND 1"
    )

    _compile_and_run(query, out_path)

    duration = _ffprobe_duration(out_path)
    assert duration == pytest.approx(1.0, abs=0.2)


def test_hflip_matches_pil_flipped_source_by_phash(tmp_path: Path) -> None:
    _require_fixture(_TESTSRC)
    out_path = tmp_path / "hflipped.mp4"
    query = f"SELECT hflip(a.frame) FROM input('{_sql_path(_TESTSRC)}') a"

    _compile_and_run(query, out_path)

    source_png = tmp_path / "source_frame.png"
    output_png = tmp_path / "output_frame.png"
    _extract_frame(_TESTSRC, 1.0, source_png)
    _extract_frame(out_path, 1.0, output_png)

    with Image.open(source_png) as source_img:
        expected = source_img.transpose(Image.Transpose.FLIP_LEFT_RIGHT)
        expected_hash = imagehash.phash(expected)
    with Image.open(output_png) as output_img:
        actual_hash = imagehash.phash(output_img)

    distance = expected_hash - actual_hash
    assert distance <= _PHASH_MAX_DISTANCE


# ---------------------------------------------------------------------------
# multi-stream (v2 / RFC-001): remap-only passthrough and audio broadcasting
# ---------------------------------------------------------------------------


def test_remap_only_stream_copies_the_selected_audio_track(tmp_path: Path) -> None:
    """`a.video[1], a.audio[2]` on a 2-audio-track file: nothing re-encoded.

    av2.mp4 tags its second audio track `language=fra`; a bare subscript with
    zero node consumers must stay a passthrough (-map + -c copy), so the
    output keeps that tag and the exact input codec.
    """
    _require_fixture(_AV2)
    out_path = tmp_path / "remap.mp4"
    query = f"SELECT a.video[1], a.audio[2] FROM input('{_sql_path(_AV2)}') a"

    graph = compile_sql(query)
    emitted = emit(graph)
    assert emitted.filter_complex == ""  # pure passthrough: no filtergraph at all

    args = build_ffmpeg_args(emitted, str(out_path))
    assert "-c:0" in args and "-c:1" in args  # both outputs are stream-copied
    args.insert(1, "-y")
    result = subprocess.run(args, capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT)
    assert result.returncode == 0, result.stderr
    assert out_path.exists()

    streams = _ffprobe_streams(out_path)
    assert [s["codec_type"] for s in streams] == ["video", "audio"]
    audio = streams[1]
    assert audio["tags"]["language"] == "fra"
    source_audio = _ffprobe_streams(_AV2)[2]  # a.audio[2] is the fra track (1-based)
    assert audio["codec_name"] == source_audio["codec_name"]


def test_reverb_broadcast_produces_a_tagged_stream_per_language_track(tmp_path: Path) -> None:
    """`reverb(a.audio, 0.3)` on a 2-audio-track file expands to two aecho
    subgraphs, one per track, and each output keeps its source language tag."""
    _require_fixture(_AV2)
    out_path = tmp_path / "reverb.mp4"
    query = f"SELECT reverb(a.audio, 0.3) FROM input('{_sql_path(_AV2)}') a"

    _compile_and_run(query, out_path)

    streams = _ffprobe_streams(out_path)
    assert [s["codec_type"] for s in streams] == ["audio", "audio"]
    assert [s["tags"]["language"] for s in streams] == ["eng", "fra"]


# ---------------------------------------------------------------------------
# UNION ALL splat: concat two dual-language sources, tracks paired by position
# ---------------------------------------------------------------------------


def test_union_splat_concatenates_both_language_tracks(tmp_path: Path) -> None:
    """The README headline, end to end.

    Both branches splat `<alias>.audio`, so UNION ALL's column matching pairs
    av2's and av3's tracks elementwise into `concat=n=2:v=1:a=2`. The two files
    tag their tracks eng/fra alike, so both concat audio pads keep the language
    they agree on -- and the run is twice as long as either source.
    """
    _require_fixture(_AV2)
    _require_fixture(_AV3)
    out_path = tmp_path / "season.mp4"
    query = (
        f"SELECT a.frame, a.audio FROM input('{_sql_path(_AV2)}') a "
        f"UNION ALL "
        f"SELECT b.frame, b.audio FROM input('{_sql_path(_AV3)}') b"
    )

    _compile_and_run(query, out_path)

    streams = _ffprobe_streams(out_path)
    assert [s["codec_type"] for s in streams] == ["video", "audio", "audio"]
    assert [s["tags"]["language"] for s in streams[1:]] == ["eng", "fra"]
    assert _ffprobe_duration(out_path) == pytest.approx(
        _ffprobe_duration(_AV2) + _ffprobe_duration(_AV3), abs=0.3
    )
